(node + NS1  :top? t)
(node - SREBF1 :measured? t )
(node + JUN :measured? t )
(node - NR1H2 :measured? t )
(node - AHR :measured? t )
(node + ZBTB7A :measured? t )
(node - ETS1 :measured? t )
(node + TP53 :measured? t )
(node - STAT3 :measured? t )
(node + ZEB2 :measured? t )
(node - MYCN :measured? t )
(node - ARNT :measured? t )
(node - STAT1 :measured? t )
(node - KLF5 :measured? t )
(node - TEAD2 :measured? t )
(node - EGR1 :measured? t )
(node - TCF12 :measured? t )
(node - NFATC1 :measured? t )
(node + HNF1A :measured? t )
(node - YY1 :measured? t )
(node - KDM5B :measured? t )
(node - TEAD1 :measured? t )
(node - MITF :measured? t )
(node - IRF4 :measured? t )
(node - FOXK2 :measured? t )
(node + FOXO1 :measured? t )
(node + NANOG :measured? t )
(node + MYC :measured? t )
(node + CREM :measured? t )
(node + HNF1B :measured? t )
(node + HNF4A :measured? t )
(node + KLF13 :measured? t )
(node + HSF1 :measured? t )
(node + GATA2 :measured? t )
(node + KLF1 :measured? t )
(node - USF2 :measured? t )
(node - SOX2 :measured? t )
(node - SP3 :measured? t )
(node - IKZF1 :measured? t )
(node + HBP1 :measured? t )
(node - MAFK :measured? t )
(node + ZEB1 :measured? t )
(node + PRKACA  )
(node + MAPK14  )
(node - AKT1  )
(node - CDK1  )
(node - JAK1  )
(node + KAT2B  )
(node + RPS6KB1  )
(node + CAMKK1  )
(node - RUNX1  )
(node + PARP1  )
(node - BRCA1  )
(node - EP300  )
(node + CSNK2A1  )
(node - HDAC1  )
(node - SUMO1  )
(node - ERBB4  )
(node - RXRB  )
(node + NR4A1  )
(node + PCBD1  )
(node + PIK3CA  )
(node + CD44  )
(node - E2F1  )
(node - EGF  )
(node + HDAC3  )
(node - YAP1  )
(node - PRKCD  )
(node - TRIM25  )
(node + NR2F2  )
(node - BLK  )
(node + ZNF652  )
(edge + PRKACA CAMKK1)
(edge + PRKACA HSF1)
(edge + PRKACA CD44)
(edge + PRKACA ZEB2)
(edge + MAPK14 TP53)
(edge + MAPK14 MYC)
(edge + MAPK14 FOXO1)
(edge + MAPK14 KAT2B)
(edge + MAPK14 JUN)
(edge + MAPK14 CSNK2A1)
(edge + MAPK14 HNF4A)
(edge + MAPK14 GATA2)
(edge + MAPK14 HBP1)
(edge - AKT1 MYC)
(edge - AKT1 FOXO1)
(edge - AKT1 NR4A1)
(edge - AKT1 GATA2)
(edge - STAT1 MYC)
(edge - CDK1 FOXO1)
(edge - JAK1 FOXO1)
(edge + KAT2B TP53)
(edge + KAT2B HNF1A)
(edge + KAT2B KLF13)
(edge + RPS6KB1 PRKACA)
(edge + RPS6KB1 MYC)
(edge + RPS6KB1 CAMKK1)
(edge + RPS6KB1 HSF1)
(edge + RPS6KB1 CREM)
(edge + CAMKK1 PCBD1)
(edge - RUNX1 MYC)
(edge + PARP1 TP53)
(edge + PARP1 ZEB1)
(edge - BRCA1 TP53)
(edge - EP300 MYC)
(edge - EP300 FOXO1)
(edge + CSNK2A1 TP53)
(edge + CSNK2A1 HDAC3)
(edge - HDAC1 TP53)
(edge - HDAC1 MYC)
(edge - HDAC1 KLF1)
(edge - SUMO1 PARP1)
(edge - ERBB4 ZNF652)
(edge - RXRB RPS6KB1)
(edge + NR4A1 NR2F2)
(edge + PCBD1 HNF1B)
(edge - YY1 JUN)
(edge + PIK3CA MAPK14)
(edge + PIK3CA MYC)
(edge + PIK3CA RPS6KB1)
(edge + PIK3CA ZBTB7A)
(edge + HNF4A FOXO1)
(edge + CD44 TP53)
(edge + CD44 NANOG)
(edge + NS1 PIK3CA)
(edge - PRKACA NFATC1)
(edge - PRKACA SREBF1)
(edge - MAPK14 NFATC1)
(edge + AKT1 STAT3)
(edge + AKT1 BRCA1)
(edge + AKT1 EP300)
(edge + AKT1 PRKCD)
(edge + AKT1 RXRB)
(edge + AKT1 TEAD1)
(edge + AKT1 ETS1)
(edge + AKT1 ARNT)
(edge + AKT1 SREBF1)
(edge - TP53 ETS1)
(edge + E2F1 MYCN)
(edge + E2F1 EGR1)
(edge + E2F1 BRCA1)
(edge + E2F1 HDAC1)
(edge + STAT3 STAT1)
(edge + STAT3 EGR1)
(edge + STAT1 ARNT)
(edge + CDK1 E2F1)
(edge + CDK1 RUNX1)
(edge + CDK1 BRCA1)
(edge + CDK1 SREBF1)
(edge + CDK1 FOXK2)
(edge + JAK1 AKT1)
(edge + JAK1 STAT3)
(edge + JAK1 STAT1)
(edge + JAK1 ETS1)
(edge + JAK1 MITF)
(edge + JAK1 IRF4)
(edge + RUNX1 HDAC1)
(edge + RUNX1 BLK)
(edge - PARP1 KDM5B)
(edge + EGF STAT3)
(edge + EGF STAT1)
(edge + EGF JAK1)
(edge + EGF ERBB4)
(edge + BRCA1 SOX2)
(edge + EP300 E2F1)
(edge + EP300 STAT3)
(edge + EP300 YY1)
(edge + EP300 ARNT)
(edge + EP300 MITF)
(edge - CSNK2A1 ARNT)
(edge - CSNK2A1 IKZF1)
(edge - HDAC3 MAFK)
(edge - HSF1 SUMO1)
(edge + YAP1 TEAD2)
(edge + YAP1 TEAD1)
(edge + SUMO1 HDAC1)
(edge + SUMO1 YAP1)
(edge + PRKCD STAT3)
(edge + PRKCD STAT1)
(edge + PRKCD KLF5)
(edge + TRIM25 CDK1)
(edge + RXRB NR1H2)
(edge + RXRB SREBF1)
(edge - NR2F2 USF2)
(edge + NR1H2 SREBF1)
(edge + ARNT ETS1)
(edge + ARNT AHR)
(edge + BLK EGF)
(edge + NFATC1 SP3)
(edge + KLF5 SREBF1)
(edge - ZNF652 TCF12)
(edge - NS1 TRIM25)
