#lang racket
(require "ltms.rkt")
(define (ex1)
   (define ltms_ (create-ltms "Simple Example" #:debugging #t))
  (define-values (x y z r)
    (values
    (tms-create-node ltms_ "x" #:assumptionp #t)
    (tms-create-node ltms_ "y" )
    (tms-create-node ltms_ "z" )
    (tms-create-node ltms_ "r" )
    ))
  (add-formula ltms_ `(:OR ,x ,y))
  (add-formula ltms_ `(:OR (:NOT ,y) ,z))
  (add-formula ltms_ `(:OR (:NOT ,z) ,r))
  (enable-assumption x ':FALSE)
  (explain-node r)
  )
(define (test-and)
  (define ltms_ (create-ltms "LTMS" #:debugging #t))
  (define-values (ok z x y)
    (values
     (tms-create-node ltms_ "ok" #:assumptionp #t)
     (tms-create-node ltms_ "z" #:assumptionp #t)
     (tms-create-node ltms_ "x" #:assumptionp #t)
     (tms-create-node ltms_ "y" #:assumptionp #t)))
  (add-formula ltms_ `(:IMPLIES ,ok (:IFF ,z (:AND ,x ,y))))
  (pretty-print-clauses ltms_)
  )
  
    
