(load "export-rxns.lisp")
(setq *pwys* (collect-pwys (all-pathways :small-molecule t) #'balanced-pwy-p))
(setq *pwy-catalyses* (collect-pwy-catalyses (all-pathways :small-molecule t) #'balanced-pwy-p))
(setq *pwy-enzymes* (collect-pwy-enzymes (all-pathways :small-molecule t) #'balanced-pwy-p))



((PWY GLUTORN-PWY (WATER GLT NADPH ATP ACETYL-COA) CO-A ACETYL-GLU ADP
  N-ACETYL-GLUTAMYL-P |Pi| NADP CPD-469 2-KETOGLUTARATE
  N-ALPHA-ACETYLORNITHINE ACET L-ORNITHINE)
 (PWY PWY0-901 (|SEC-tRNAs| SER ATP CPD-678) SEPO3 |Charged-SEC-tRNAs|
  WATER |Pi| AMP PPI |L-seryl-SEC-tRNAs|)
 (PWY ALANINE-SYN2-PWY (GLT PYRUVATE) L-ALPHA-ALANINE 2-KETOGLUTARATE)
 (PWY ALANINE-VALINESYN-PWY (PYRUVATE GLT) 2-KETOGLUTARATE VAL
  D-ALANINE 2-KETO-ISOVALERATE L-ALPHA-ALANINE)
 (PWY PWY0-1021 (CYS PROT-CYS) ENZYME-S-SULFANYLCYSTEINE
  L-ALPHA-ALANINE)
 (PWY ASPARAGINESYN-PWY (AMMONIA L-ASPARTATE ATP GLN WATER) GLT AMP PPI
  ASN)
 (PWY ASPARTATESYN-PWY (OXALACETIC_ACID GLT) 2-KETOGLUTARATE
  L-ASPARTATE)
 (PWY GLUTDEG-PWY (OXALACETIC_ACID GLT) 2-KETOGLUTARATE L-ASPARTATE
  AMMONIA FUM)
 (PWY PWY-5155 (L-ASPARTATE) CARBON-DIOXIDE B-ALANINE)
 (PWY CYSTSYN-PWY (HS SER ACETYL-COA) CO-A ACETYLSERINE ACET CYS)
 (PWY GLUTSYN-PWY (GLN 2-KETOGLUTARATE NADPH) NADP GLT)
 (PWY GLUTSYNIII-PWY (2-KETOGLUTARATE AMMONIA NADPH) NADP WATER GLT)
 (PWY GLNSYN-PWY (AMMONIA GLT ATP) |Pi| ADP GLN)
 (PWY GLYSYN-PWY (SER THF) WATER GLY METHYLENE-THF)
 (PWY HISTSYN-PWY (ATP PRPP GLN NAD) HIS NADH HISTIDINAL |Pi|
  HISTIDINOL 2-KETOGLUTARATE L-HISTIDINOL-P WATER IMIDAZOLE-ACETOL-P
  GLT AICAR D-ERYTHRO-IMIDAZOLE-GLYCEROL-P
  PHOSPHORIBULOSYL-FORMIMINO-AICAR-P PHOSPHORIBOSYL-AMP
  PHOSPHORIBOSYL-FORMIMINO-AICAR-P PPI PHOSPHORIBOSYL-ATP)
 (PWY ILEUSYN-PWY (THR PYRUVATE NADPH GLT) WATER
  2-KETO-3-METHYL-VALERATE 2-KETOGLUTARATE ILE NADP
  1-KETO-2-METHYLVALERATE CARBON-DIOXIDE 2-ACETO-2-HYDROXY-BUTYRATE
  AMMONIA 2-OXOBUTANOATE)
 (PWY LEUSYN-PWY (2-KETO-ISOVALERATE ACETYL-COA GLT NAD) PROTON NADH
  CPD-7100 2-KETOGLUTARATE LEU WATER CPD-9451 CO-A
  3-CARBOXY-3-HYDROXY-ISOCAPROATE CARBON-DIOXIDE 2K-4CH3-PENTANOATE
  2-D-THREO-HYDROXY-3-CARBOXY-ISOCAPROATE)
 (PWY DAPLYSINESYN-PWY
  (L-ASPARTATE ATP NADPH PYRUVATE |NAD(P)H| PROTON SUC-COA GLT)
  MESO-DIAMINOPIMELATE CARBON-DIOXIDE LYS SUC LL-DIAMINOPIMELATE
  |n-succinylll-2,6-diaminopimelate| 2-KETOGLUTARATE CO-A
  N-SUCCINYL-2-AMINO-6-KETOPIMELATE |NAD(P)|
  DELTA{1}-PIPERIDEINE-2-6-DICARBOXYLATE |2,3-dihydrodipicolinate|
  WATER L-ASPARTATE-SEMIALDEHYDE |Pi| NADP ADP L-BETA-ASPARTYL-P)
 (PWY HOMOSER-METSYN-PWY
  (CYS WATER 5-METHYL-THF CPD-1302 HOMO-SER SUC-COA) CO-A
  O-SUCCINYL-L-HOMOSERINE CPD-1301 THF MET HOMO-CYS AMMONIA PYRUVATE
  L-CYSTATHIONINE SUC)
 (PWY HOMOSERSYN-PWY (|NAD(P)H| PROTON NADPH L-ASPARTATE ATP) ADP
  L-BETA-ASPARTYL-P L-ASPARTATE-SEMIALDEHYDE |Pi| NADP |NAD(P)|
  HOMO-SER)
 (PWY PHESYN (CHORISMATE GLT) 2-KETOGLUTARATE PHE CARBON-DIOXIDE WATER
  PHENYL-PYRUVATE PREPHENATE)
 (PWY PROSYN-PWY (2-KETOGLUTARATE AMMONIA NADPH ATP PROTON |NAD(P)H|)
  |l-delta(1)-pyrroline_5-carboxylate| |NAD(P)| PRO |Pi|
  L-GLUTAMATE_GAMMA-SEMIALDEHYDE ADP L-GLUTAMATE-5-P NADP WATER GLT)
 (PWY SERSYN-PWY (WATER G3P NAD GLT) 2-KETOGLUTARATE 3-P-SERINE NADH
  3-P-HYDROXYPYRUVATE |Pi| SER)
 (PWY HOMOSER-THRESYN-PWY (WATER HOMO-SER ATP) ADP
  O-PHOSPHO-L-HOMOSERINE THR |Pi|)
 (PWY TRPSYN-PWY (SER CHORISMATE GLN PRPP) CARBON-DIOXIDE
  INDOLE-3-GLYCEROL-P CARBOXYPHENYLAMINO-DEOXYRIBULOSE-P PPI
  |N-(5-PHOSPHORIBOSYL)-ANTHRANILATE| GLT PYRUVATE ANTHRANILATE GAP
  INDOLE WATER TRP)
 (PWY TYRSYN (CHORISMATE NAD GLT) 2-KETOGLUTARATE TYR NADH
  CARBON-DIOXIDE P-HYDROXY-PHENYLPYRUVATE PREPHENATE)
 (PWY VALSYN-PWY (PYRUVATE NADPH PROTON GLT) WATER 2-KETO-ISOVALERATE
  2-KETOGLUTARATE VAL NADP DIOH-ISOVALERATE CARBON-DIOXIDE
  2-ACETO-LACTATE)
 (PWY TRNA-CHARGING-PWY
  (|GLY-tRNAs| GLY ATP |HIS-tRNAs| HIS LYS |LYS-tRNAs| |MET-tRNAs| MET
   |PHE-tRNAs| PHE |PRO-tRNAs| PRO |SER-tRNAs| SER |THR-tRNAs| THR TRP
   |TRP-tRNAs| |TYR-tRNAs| TYR |ASP-tRNAs| L-ASPARTATE |ASN-tRNAs| ASN
   |ALA-tRNAs| L-ALPHA-ALANINE |VAL-tRNAs| VAL |LEU-tRNAs| LEU
   |ILE-tRNAs| ILE |GLT-tRNAs| GLT |GLN-tRNAs| GLN |CYS-tRNAs| CYS
   |ARG-tRNAs| ARG)
  |Charged-ARG-tRNAs| |Charged-CYS-tRNAs| |Charged-GLN-tRNAs|
  |Charged-GLT-tRNAs| |Charged-ILE-tRNAs| |Charged-LEU-tRNAs|
  |Charged-VAL-tRNAs| |Charged-ALA-tRNAs| |Charged-ASN-tRNAs|
  |Charged-ASP-tRNAs| |Charged-TYR-tRNAs| |Charged-TRP-tRNAs|
  |Charged-THR-tRNAs| |Charged-SER-tRNAs| |Charged-PRO-tRNAs|
  |Charged-PHE-tRNAs| |Charged-MET-tRNAs| |Charged-LYS-tRNAs|
  |Charged-HIS-tRNAs| AMP PPI |Charged-GLY-tRNAs|)
 (PWY GLUCONEO-PWY (NADP MAL ATP DIHYDROXY-ACETONE-PHOSPHATE) GLC-6-P
  FRUCTOSE-6P FRUCTOSE-16-DIPHOSPHATE NAD GAP DPG G3P 2-PG ADP
  OXALACETIC_ACID AMP |Pi| NADH PYRUVATE NADPH CARBON-DIOXIDE WATER
  PHOSPHO-ENOL-PYRUVATE)
 (PWY GLYCOCAT-PWY (ATP WATER |Pi| |Glycogens|) GLC CPD0-971
  ALPHA-GLC-6-P CPD0-1027 MALTOTETRAOSE GLC-1-P MALTOTRIOSE
  ALPHA-GLUCOSE MALTOSE ADP GLC-6-P)
 (PWY GALACTMETAB-PWY (UTP |D-Galactose| ATP) ADP GALACTOSE-1P
  UDP-GALACTOSE GLC-1-P PPI UDP-GLUCOSE)
 (PWY PWY-1269 (RIBULOSE-5P WATER PHOSPHO-ENOL-PYRUVATE CTP) PPI
  CMP-KDO KDO |Pi| KDO-8P ARABINOSE-5P)
 (PWY PWY0-1241 (D-SEDOHEPTULOSE-7-P WATER ATP) ADP
  D-BETA-D-HEPTOSE-17-DIPHOSPHATE PPI ADP-D-GLYCERO-D-MANNO-HEPTOSE
  |Pi| D-BETA-D-HEPTOSE-1-P ADP-L-GLYCERO-D-MANNO-HEPTOSE
  D-ALPHABETA-D-HEPTOSE-7-PHOSPHATE)
 (PWY DTDPRHAMSYN-PWY (GLC-1-P TTP NADPH) DTDP-DEOH-DEOXY-MANNOSE
  DTDP-RHAMNOSE NADP DTDP-DEOH-DEOXY-GLUCOSE WATER PPI DTDP-D-GLUCOSE)
 (PWY TRESYN-PWY (WATER UDP-GLUCOSE ALPHA-GLC-6-P) TREHALOSE-6P UDP
  |Pi| TREHALOSE)
 (PWY GLYCOGENSYNTH-PWY (GLC-1-P ATP) |1-4-alpha-D-Glucan| ADP
  |6-alpha-D--1-4-alpha-D-Glucano--Glucan| PPI ADP-D-GLUCOSE)
 (PWY COLANSYN-PWY (NADPH NAD UTP |D-Galactose| ATP GDP FRUCTOSE-6P)
  MANNOSE-6P MANNOSE-1P |Pi| GDP-MANNOSE
  GDP-4-DEHYDRO-6-DEOXY-D-MANNOSE WATER ADP GALACTOSE-1P UDP-GALACTOSE
  GLC-1-P PPI UDP-GLUCOSE UDP-GLUCURONATE NADH
  GUANOSINE_DIPHOSPHATE_FUCOSE NADP)
 (PWY ECASYN-PWY
  (GLC-1-P TTP GLT UDP-N-ACETYL-D-GLUCOSAMINE ACETYL-COA NAD
   UNDECAPRENYL-P)
  GLCNAC-PP-LIPID UMP UDP C55-PP-GLCNAC-MANNACA PROTON NADH UDP-MANNACA
  TDP C55-PP-GLCNAC-MANNACA-FUC4NAC CO-A TDP-FUC4NAC UDP-MANNAC
  2-KETOGLUTARATE TDP-D-FUCOSAMINE PPI DTDP-D-GLUCOSE
  DTDP-DEOH-DEOXY-GLUCOSE WATER)
 (PWY KDOSYN-PWY (CMP-KDO LIPID-IV-A) KDO-LIPID-IVA CMP KDO2-LIPID-IVA)
 (PWY MANGDPMET-PWY (FRUCTOSE-6P ATP WATER) MANNOSE GDP ADP |Pi|
  GDP-MANNOSE MANNOSE-1P MANNOSE-6P)
 (PWY NAGLIPASYN-PWY
  (3-OHMYRISTOYL-ACP UDP-N-ACETYL-D-GLUCOSAMINE WATER ATP) UDP
  BISOHMYR-GLC ADP LIPID-IV-A UMP BISOHMYR-GLUCOSAMINYL-1P OH-MYRISTOYL
  ACET UDP-OHMYR-GLUCOSAMINE ACP UDP-OHMYR-ACETYLGLUCOSAMINE)
 (PWY UDPNAGSYN-PWY (FRUCTOSE-6P GLN ACETYL-COA UTP) PPI
  UDP-N-ACETYL-D-GLUCOSAMINE CO-A N-ACETYL-D-GLUCOSAMINE-1-P GLT
  D-GLUCOSAMINE-6-P GLUCOSAMINE-1P)
 (PWY PEPTIDOGLYCANSYN-PWY
  (UNDECAPRENYL-P D-ALANINE ATP MESO-DIAMINOPIMELATE GLT
   L-ALPHA-ALANINE UDP-N-ACETYL-D-GLUCOSAMINE NADPH
   PHOSPHO-ENOL-PYRUVATE)
  UDP-ACETYL-CARBOXYVINYL-GLUCOSAMINE UDP-N-ACETYLMURAMATE NADP UDP C6
  C1 UDP-ACETYLMURAMOYL-ALA UDP-AA-GLUTAMATE D-GLT
  UDP-AAGM-DIAMINOHEPTANEDIOATE ADP |Pi| D-ALA-D-ALA UMP C5)
 (PWY NONMEVIPP-PWY
  (ATP CTP |NAD(P)H| PROTON |Protein-Dithiols| NADPH PYRUVATE GAP)
  DEOXYXYLULOSE-5P CARBON-DIOXIDE NADP
  2-C-METHYL-D-ERYTHRITOL-4-PHOSPHATE |Protein-Disulfides|
  HYDROXY-METHYL-BUTENYL-DIP WATER |NAD(P)| |delta(3)-isopentenyl-pp|
  PPI 4-CYTIDINE-5-DIPHOSPHO-2-C ADP
  2-PHOSPHO-4-CYTIDINE-5-DIPHOSPHO-2-C-MET
  2C-METH-D-ERYTHRITOL-CYCLODIPHOSPHATE CMP CPD-4211)
 (PWY PWY-5123 (|delta(3)-isopentenyl-pp|) GERANYL-PP FARNESYL-PP PPI
  CPD-4211)
 (PWY SAM-PWY (ATP MET WATER) S-ADENOSYLMETHIONINE PPI |Pi|)
 (PWY COA-PWY (PANTOTHENATE ATP CYS CTP) DEPHOSPHO-COA CO-A
  CARBON-DIOXIDE PANTETHEINE-P R-4-PHOSPHOPANTOTHENOYL-L-CYSTEINE CMP
  PPI ADP 4-P-PANTOTHENATE)
 (PWY P2-PWY (DEPHOSPHO-COA ATP APO-CITRATE-LYASE) PPI
  HOLO-CITRATE-LYASE ADENINE 2-5-TRIPHOSPHORIBOSYL-3-DEPHOSPHO-)
 (PWY PWY0-1275
  (S-ADENOSYLMETHIONINE CPD-7046 |Non-lipoylated-domains| CPD-195 ATP)
  PPI AMP |Octanoylated-domains| MET CH33ADO |Lipoylated-domains|)
 (PWY PWY0-501
  (CPD-195 ATP |Non-lipoylated-domains| S-ADENOSYLMETHIONINE CPD-7046)
  MET CH33ADO |Lipoylated-domains| ACP |Octanoylated-domains| PPI AMP
  OCTANOYL-ACP)
 (PWY PWY0-522 (|Non-lipoylated-domains| LIPOIC-ACID ATP) PPI AMP
  |Lipoylated-domains|)
 (PWY NADPHOS-DEPHOS-PWY (WATER ATP NADPH) NADH ADP NADP |Pi| NAD)
 (PWY PYRIDNUCSAL-PWY (ATP GLN WATER PRPP) DEAMIDO-NAD
  NICOTINAMIDE_NUCLEOTIDE NICOTINATE_NUCLEOTIDE AMMONIA NIACINE
  ADENOSINE_DIPHOSPHATE_RIBOSE NIACINAMIDE RIBOSE-5P GLT NAD PPI AMP)
 (PWY PYRIDNUCSYN-PWY
  (OXYGEN-MOLECULE L-ASPARTATE DIHYDROXY-ACETONE-PHOSPHATE PRPP ATP
   AMMONIA GLN)
  DEAMIDO-NAD GLT NAD AMP NICOTINATE_NUCLEOTIDE PPI CARBON-DIOXIDE |Pi|
  WATER QUINOLINATE IMINOASPARTATE HYDROGEN-PEROXIDE)
 (PWY PWY-5783 (|delta(3)-isopentenyl-pp| FARNESYL-PP)
  GERANYLGERANYL-PP ALL-TRANS-PENTAPRENYL-DIPHOSPHATE
  ALL-TRANS-HEXAPRENYL-DIPHOSPHATE ALL-TRANS-HEPTAPRENYL-DIPHOSPHATE
  OCTAPRENYL-DIPHOSPHATE PPI)
 (PWY PWY-5785 (|delta(3)-isopentenyl-pp| FARNESYL-PP) CPD0-1028
  CPD-9457 CPD-9456 CPD-9455 CPD-9454 CPD-9453 CPD-9452 PPI
  UNDECAPRENYL-DIPHOSPHATE)
 (PWY PWY-5194 (S-ADENOSYLMETHIONINE UROPORPHYRINOGEN-III FE+2 NAD)
  NADH SIROHYDROCHLORIN SIROHEME PROTON CPD-9038
  DIHYDROSIROHYDROCHLORIN ADENOSYL-HOMO-CYS)
 (PWY HEMESYN2-PWY
  (OXYGEN-MOLECULE S-ADENOSYLMETHIONINE UROPORPHYRINOGEN-III FE+2)
  PROTOPORPHYRIN_IX PROTOHEME PROTON COPROPORPHYRINOGEN_III CH33ADO MET
  WATER CARBON-DIOXIDE PROTOPORPHYRINOGEN)
 (PWY MENAQUINONESYN-PWY
  (2-KETOGLUTARATE CHORISMATE ATP S-ADENOSYLMETHIONINE
   OCTAPRENYL-DIPHOSPHATE)
  DEMETHYLMENAQUINONE ADENOSYL-HOMO-CYS VITAMIN_K_{2}
  DIHYDROXYNAPHTHOATE CO-A O-SUCCINYLBENZOYL-COA PPI AMP WATER
  O-SUCCINYLBENZOATE ISOCHORISMATE CARBON-DIOXIDE PYRUVATE
  SUCCINYL-OH-CYCLOHEXADIENE-COOH)
 (PWY UBISYN-PWY
  (CHORISMATE OCTAPRENYL-DIPHOSPHATE OXYGEN-MOLECULE
   S-ADENOSYLMETHIONINE)
  OCTAPRENYL-METHYL-OH-METHOXY-BENZQ UBIQUINONE-8
  OCTAPRENYL-METHYL-METHOXY-BENZQ OCTAPRENYL-METHOXY-BENZOQUINONE WATER
  ADENOSYL-HOMO-CYS 2-OCTAPRENYL-6-METHOXYPHENOL
  2-OCTAPRENYL-6-HYDROXYPHENOL CARBON-DIOXIDE 2-OCTAPRENYLPHENOL
  3-OCTAPRENYL-4-HYDROXYBENZOATE PPI PYRUVATE |4-hydroxybenzoate|)
 (PWY GLUT-REDOX-PWY (NADPH PROTON |Ox-Glutaredoxins|)
  |Red-Glutaredoxins| OXIDIZED-GLUTATHIONE NADP GLUTATHIONE)
 (PWY GLUTATHIONESYN-PWY (GLY ATP CYS GLT) L-GAMMA-GLUTAMYLCYSTEINE ADP
  |Pi| GLUTATHIONE)
 (PWY THIOREDOX-PWY (E- NADP) PROTON NADPH |Ox-Thioredoxin|
  |Red-Thioredoxin|)
 (PWY PWY-5188 (GLT ATP NADPH PROTON) UROPORPHYRINOGEN-III
  HYDROXYMETHYLBILANE AMMONIA PORPHOBILINOGEN WATER 5-AMINO-LEVULINATE
  |GLT-tRNAs| NADP GLUTAMATE-1-SEMIALDEHYDE AMP PPI
  |Charged-GLT-tRNAs|)
 (PWY RIBOSYN2-PWY (GTP NADPH PROTON RIBULOSE-5P ATP) ADP FMN FAD
  RIBOFLAVIN WATER DIMETHYL-D-RIBITYL-LUMAZINE |Pi|
  AMINO-RIBOSYLAMINO-1H-3H-PYR-DIONE DIHYDROXY-BUTANONE-P NADP CPD-1086
  AMMONIA CPD-602 FORMATE DIAMINO-OH-PHOSPHORIBOSYLAMINO-PYR PPI)
 (PWY BIOTIN-SYNTHESIS-PWY
  (L-ALPHA-ALANINE CPD-558 S-ADENOSYLMETHIONINE CPD-249 ATP) ADP |Pi|
  DETHIOBIOTIN MET CH33ADO BIOTIN DIAMINONONANOATE
  S-ADENOSYL-4-METHYLTHIO-2-OXOBUTANOATE 8-AMINO-7-OXONONANOATE CO-A
  CARBON-DIOXIDE)
 (PWY PWY-5448 (THR) NADH AMINO-OXOBUT CARBON-DIOXIDE AMINO-ACETONE NAD
  1-AMINO-PROPAN-2-OL)
 (PWY COBALSYN-PWY
  (COBINAMIDE ATP NICOTINATE_NUCLEOTIDE DIMETHYLBENZIMIDAZOLE WATER GTP
   COB-I-ALAMIN)
  PPI ADENOSYLCOBINAMIDE-GDP GMP ADENOSYLCOBALAMIN |Pi| ALPHA-RIBAZOLE
  ADP ADENOSYLCOBINAMIDE-P ALPHA-RIBAZOLE-5-P NIACINE P3I
  ADENOSYLCOBINAMIDE)
 (PWY 1CMET2-PWY
  (GLT |7,8-dihydropteroate| ATP DUMP HOMO-CYS |NAD(P)H| PROTON NAD
   SER)
  FORMYL-THF-GLU-N 10-FORMYL-THF FORMATE NADP WATER GLY
  |5,10-methenyl-thf| NADPH NADH CARBON-DIOXIDE AMMONIA METHYLENE-THF
  |NAD(P)| 5-METHYL-THF THF MET TMP ADP |Pi| DIHYDROFOLATE)
 (PWY FOLSYN-PWY
  (5-PHOSPHO-RIBOSYL-GLYCINEAMIDE GTP WATER ATP NADPH
   |5,10-methenyl-thf| GLN CHORISMATE)
  PYRUVATE P-AMINO-BENZOATE |7,8-dihydropteroate| GLT
  4-AMINO-4-DEOXYCHORISMATE 10-FORMYL-THF ADP DIHYDROFOLATE NADP AMP
  DIHYDROPTERIN-CH2OH-PP AMINO-OH-HYDROXYMETHYL-DIHYDROPTERIDINE
  GLYCOLALDEHYDE |Pi| DIHYDRO-NEO-PTERIN PPI DIHYDRONEOPTERIN-P
  DIHYDRONEOPTERIN-P3 FORMATE 5-P-RIBOSYL-N-FORMYLGLYCINEAMIDE THF)
 (PWY PWY-2161 (GLT ATP METHYLENE-THF GLY WATER FORMATE) 10-FORMYL-THF
  THF SER THF-GLU-N METHYLENE-THF-GLU-N |Pi| ADP FORMYL-THF-GLU-N)
 (PWY PANTO-PWY
  (VAL 2-KETOGLUTARATE WATER METHYLENE-THF NADPH B-ALANINE ATP) AMP PPI
  PANTOTHENATE NADP L-PANTOATE THF 2-DEHYDROPANTOATE GLT
  2-KETO-ISOVALERATE)
 (PWY PLPSAL-PWY
  (ATP PYRIDOXAL OXYGEN-MOLECULE WATER PYRIDOXAMINE PYRIDOXINE)
  PYRIDOXINE-5P PYRIDOXAMINE-5P AMMONIA HYDROGEN-PEROXIDE
  PYRIDOXAL_PHOSPHATE ADP)
 (PWY PYRIDOXSYN-PWY
  (NAD GLT PYRUVATE GAP ERYTHROSE-4P OXYGEN-MOLECULE)
  PYRIDOXAL_PHOSPHATE HYDROGEN-PEROXIDE PROTON ERYTHRONATE-4P
  DEOXYXYLULOSE-5P WATER |Pi| PYRIDOXINE-5P
  3OH-4P-OH-ALPHA-KETOBUTYRATE 2-KETOGLUTARATE 4-PHOSPHONOOXY-THREONINE
  CARBON-DIOXIDE 1-AMINO-PROPAN-2-ONE-3-PHOSPHATE
  2-AMINO-3-OXO-4-PHOSPHONOOXYBUTYRATE NADH)
 (PWY KDO-LIPASYN-PWY (MYRISTOYL-ACP KDO2-LIPID-IVA LAUROYL-ACP)
  KDO2-LAUROYL-LIPID-IVA ACP KDO2-LIPID-A)
 (PWY LIPA-CORESYN-PWY
  (ADP-L-GLYCERO-D-MANNO-HEPTOSE UDP-GLUCOSE UDP-GALACTOSE ATP
   KDO2-LIPID-A)
  CPD0-929 CPD0-930 CPD0-932 CPD0-933 CPD0-934 CPD0-935 CPD0-936
  CPD0-937 UDP CPD0-938 ADP CPD0-939)
 (PWY PWY0-1264 (ACETYL-COA CARBON-DIOXIDE ATP |BCCP-monomers| BIOTIN)
  AMP PPI |BCCP-biotin-monomers| ADP |Pi| |Carboxybiotin-BCCP|
  |BCCP-dimers| MALONYL-COA)
 (PWY FASYN-ELONG-PWY (MALONYL-ACP NADPH NADH) WATER TRANS-D2-ENOYL-ACP
  NAD ACYL-ACP NADP OH-ACYL-ACP CARBON-DIOXIDE B-KETOACYL-ACP ACP)
 (PWY FASYN-INITIAL-PWY (ATP ACETYL-COA HCO3 PROTON ACP) |All-ACPs|
  MALONYL-ACP ACETYL-ACP CARBON-DIOXIDE CO-A |Acetoacetyl-ACPs| ADP
  |Pi| MALONYL-COA)
 (PWY PWY0-862 (BETA-HYDROXYDECANOYL-ACP MALONYL-ACP NADPH)
  CIS-DELTA5-DODECENOYL-ACP TRANS-DELTA3-CIS-DELTA5-DODECENOYL-ACP NADP
  BETA-HYDROXY-CIS-DELTA5-DODECENOYL-ACP CIS-DELTA3-DECENOYL-ACP
  CARBON-DIOXIDE ACP BETA-KETO-CIS-DELTA5-DODECENOYL-ACP WATER
  TRANS-D2-DECENOYL-ACP)
 (PWY PWY0-541
  (|Phospholipid-Olefinic-Fatty-Acids| S-ADENOSYLMETHIONINE)
  ADENOSYL-HOMO-CYS |Phospholipid-Cyclopropane-Fatty-Acids|)
 (PWY PWY-5667
  (DIHYDROXY-ACETONE-PHOSPHATE |NAD(P)H| PROTON |Fatty-Acyl-CoA| CTP)
  CDPDIACYLGLYCEROL PPI L-PHOSPHATIDATE CO-A ACYL-SN-GLYCEROL-3P
  |NAD(P)| GLYCEROL-3P)
 (PWY PWY-5669 (CDPDIACYLGLYCEROL SER) L-1-PHOSPHATIDYL-SERINE CMP
  CARBON-DIOXIDE L-1-PHOSPHATIDYL-ETHANOLAMINE)
 (PWY PWY0-1319
  (ACYL-ACP DIHYDROXY-ACETONE-PHOSPHATE |NAD(P)H| PROTON CTP)
  CDPDIACYLGLYCEROL PPI |NAD(P)| GLYCEROL-3P ACYL-SN-GLYCEROL-3P ACP
  L-PHOSPHATIDATE)
 (PWY PWY-5668 (CDPDIACYLGLYCEROL GLYCEROL-3P WATER) |Pi|
  L-1-PHOSPHATIDYL-GLYCEROL GLYCEROL CARDIOLIPIN
  L-1-PHOSPHATIDYL-GLYCEROL-P CMP)
 (PWY PPGPPMET-PWY (ATP GTP WATER) |Pi| GDP PPI GDP-TP
  GUANOSINE-5DP-3DP AMP)
 (PWY DENOVOPURINE2-PWY
  (ATP |Red-Glutaredoxins| |Reduced-flavodoxins| HCO3 |Red-Thioredoxin|
   GLN AMMONIA NAD L-ASPARTATE 10-FORMYL-THF FORMATE GLY PRPP)
  5-P-BETA-D-RIBOSYL-AMINE 5-PHOSPHO-RIBOSYL-GLYCINEAMIDE
  5-P-RIBOSYL-N-FORMYLGLYCINEAMIDE
  5-PHOSPHORIBOSYL-N-FORMYLGLYCINEAMIDINE
  5-PHOSPHORIBOSYL-5-AMINOIMIDAZOLE P-RIBOSYL-4-SUCCCARB-AMINOIMIDAZOLE
  AICAR PHOSPHORIBOSYL-FORMAMIDO-CARBOXAMIDE THF IMP ADENYLOSUCC FUM
  XANTHOSINE-5-PHOSPHATE NADH AMP PPI GMP GLT GDP GTP |Ox-Thioredoxin|
  PHOSPHORIBOSYL-CARBOXY-AMINOIMIDAZOLE |Pi| CPD0-181
  |Oxidized-flavodoxins| DADP WATER |Ox-Glutaredoxins| DGDP DGTP ADP
  DATP)
 (PWY SALVADEHYPOX-PWY (NAD ATP PRPP) RIBOSE-5P AMP HYPOXANTHINE
  RIBOSE-1P DEOXYINOSINE DEOXY-RIBOSE-1P ADENINE |Pi| ADENOSINE PPI
  DEOXYADENOSINE WATER INOSINE AMMONIA ADP IMP NADH URATE XANTHINE
  PROTON)
 (PWY SALVPURINE2-PWY
  (GUANINE PRPP DEOXY-RIBOSE-1P ATP WATER XANTHOSINE)
  XANTHOSINE-5-PHOSPHATE RIBOSE-1P XANTHINE AMMONIA ADP DEOXYGUANOSINE
  GMP PPI |Pi| GUANOSINE)
 (PWY PWY-5686 (PRPP OXYGEN-MOLECULE L-ASPARTATE ATP GLN HCO3) ADP GLT
  CARBAMOYL-P |Pi| CARBAMYUL-L-ASPARTATE WATER DI-H-OROTATE OROTATE
  HYDROGEN-PEROXIDE PPI OROTIDINE-5-PHOSPHATE UMP CARBON-DIOXIDE)
 (PWY PWY-5687 (GLN WATER UMP) UDP UTP GLT CTP |Pi| ADP ATP CDP)
 (PWY PWY0-163 (CYTIDINE GTP WATER CYTOSINE |Pi| ATP PRPP) PPI CTP ADP
  CDP RIBOSE-1P URIDINE URACIL AMMONIA UMP GDP CMP)
 (PWY PWY0-166
  (CTP |Reduced-flavodoxins| UTP CDP |Red-Glutaredoxins| UDP
   |Red-Thioredoxin| ATP METHYLENE-THF)
  AMMONIA PPI DUMP DIHYDROFOLATE TMP TDP ADP TTP |Ox-Thioredoxin| DUDP
  |Ox-Glutaredoxins| DCDP DUTP WATER |Oxidized-flavodoxins| DCTP)
 (PWY PWY0-181 (ATP THYMINE WATER DEOXYCYTIDINE) DEOXYURIDINE AMMONIA
  DUMP URACIL DEOXY-RIBOSE-1P |Pi| THYMIDINE ADP TMP)
 (PWY ARO-PWY
  (|NAD(P)H| PROTON PHOSPHO-ENOL-PYRUVATE ERYTHROSE-4P NADPH ATP)
  CHORISMATE 3-ENOLPYRUVYL-SHIKIMATE-5P ADP SHIKIMATE-5P NADP
  3-DEHYDRO-SHIKIMATE WATER DEHYDROQUINATE |Pi|
  3-DEOXY-D-ARABINO-HEPTULOSONATE-7-P |NAD(P)| SHIKIMATE)
 (PWY PWY0-661 (ATP RIBOSE-5P) RIBOSE-15-BISPHOSPHATE RIBOSE-1P ADP
  PRPP)
 (PWY PWY0-662 (ATP RIBOSE-5P) AMP PRPP)
 (PWY BSUBPOLYAMSYN-PWY (S-ADENOSYLMETHIONINE PUTRESCINE)
  5-METHYLTHIOADENOSINE SPERMIDINE S-ADENOSYLMETHIONINAMINE
  CARBON-DIOXIDE)
 (PWY PWY0-1303 (LYS S-ADENOSYLMETHIONINAMINE) 5-METHYLTHIOADENOSINE
  CPD0-1065 CADAVERINE CARBON-DIOXIDE)
 (PWY PWY0-823 (WATER ARG) AGMATHINE CARBON-DIOXIDE PUTRESCINE UREA)
 (PWY BETSYN-PWY (NAD WATER CHOLINE |Acceptor|) |Donor-H2|
  BETAINE_ALDEHYDE NADH BETAINE)
 (PWY PWY-40 (WATER ARG) AGMATHINE CARBON-DIOXIDE PUTRESCINE UREA)
 (PWY PWY-46 (L-ORNITHINE) PUTRESCINE CARBON-DIOXIDE)
 (PWY ENTBACSYN-PWY (ATP SER NAD WATER CHORISMATE) ISOCHORISMATE
  DIHYDRO-DIOH-BENZOATE PYRUVATE 2-3-DIHYDROXYBENZOATE NADH
  ENTEROBACTIN AMP PPI)
 (PWY PWY0-1280 (NAD GLYCOL WATER) GLYCOLLATE NADH GLYCOLALDEHYDE)
 (PWY ETOH-ACETYLCOA-ANA-PWY (NAD CO-A ETOH) ACETALD ACETYL-COA NADH)
 (PWY GLYCEROLMETAB-PWY (NAD GLYCEROL) DIHYDROXYACETONE NADH)
 (PWY PWY0-381
  (WATER |a glycerophosphodiester| GLYCEROL ATP UBIQUINONE-8)
  UBIQUINOL-8 DIHYDROXY-ACETONE-PHOSPHATE ADP GLYCEROL-3P |Alcohols|)
 (PWY PWY-5386 (|Unknown-Quinones| WATER METHYL-GLYOXAL)
  S-LACTOYL-GLUTATHIONE D-LACTATE GLUTATHIONE |Unknown-Quinols|
  PYRUVATE)
 (PWY PWY-5453 (NADH PROTON METHYL-GLYOXAL NADPH) NADP ACETOL NAD
  |PROPANE-1,2-DIOL|)
 (PWY PWY-901 (|Unknown-Quinones| METHYL-GLYOXAL WATER) D-LACTATE
  |Unknown-Quinols| PYRUVATE)
 (PWY PWY0-1315 (NADH LACTALD) |PROPANE-1,2-DIOL| NAD)
 (PWY PWY0-1317 (|Acceptor| WATER NAD LACTALD) L-LACTATE NADH PYRUVATE
  |Donor-H2|)
 (PWY 2PHENDEG-PWY (WATER NAD OXYGEN-MOLECULE PHENYLETHYLAMINE)
  PHENYLACETALDEHYDE AMMONIA HYDROGEN-PEROXIDE PHENYLACETATE NADH)
 (PWY GLUAMCAT-PWY (WATER N-ACETYL-D-GLUCOSAMINE-6-P) AMMONIA
  FRUCTOSE-6P D-GLUCOSAMINE-6-P ACET)
 (PWY 4AMINOBUTMETAB-PWY
  (WATER NAD NADP 2-KETOGLUTARATE 4-AMINO-BUTYRATE) SUCC-S-ALD GLT
  PROTON NADPH SUC NADH)
 (PWY PWY-5698 (WATER S-ALLANTOIN) ALLANTOATE CARBON-DIOXIDE CPD-598
  CPD-1091 AMMONIA)
 (PWY CARNMET-PWY (CARNITINE |Donor-H2|) GAMMA-BUTYROBETAINYL-COA
  |Acceptor| GAMMA-BUTYROBETAINE L-CARNITINYL-COA WATER
  CROTONOBETAINYL-COA)
 (PWY PUTDEG-PWY (PUTRESCINE 2-KETOGLUTARATE NAD WATER) PROTON NADH
  4-AMINO-BUTYRATE GLT 4-AMINO-BUTYRALDEHYDE)
 (PWY PWY0-1221 (PUTRESCINE ATP WATER OXYGEN-MOLECULE |NAD(P)|) GLT
  4-AMINO-BUTYRATE PROTON |NAD(P)H| GAMMA-GLUTAMYL-GAMMA-AMINOBUTYRATE
  AMMONIUM HYDROGEN-PEROXIDE GAMMA-GLUTAMYL-GAMMA-AMINOBUTYRALDEH |Pi|
  ADP GAMMA-GLUTAMYL-PUTRESCINE)
 (PWY PWY-5084 (NAD CO-A 2-KETOGLUTARATE) CARBON-DIOXIDE
  |Oxo-glutarate-dehydro-suc-DH-lipoyl|
  |Oxo-glutarate-dehydrogenase-DH-lipoyl| SUC-COA PROTON NADH
  |Oxo-glutarate-dehydrogenase-lipoyl|)
 (PWY ALADEG-PWY (WATER L-ALPHA-ALANINE) D-ALANINE AMMONIA PYRUVATE)
 (PWY AST-PWY (WATER NAD 2-KETOGLUTARATE ARG SUC-COA) CO-A CPD-421
  CARBON-DIOXIDE AMMONIA N2-SUCCINYLORNITHINE CPD-822 PROTON NADH
  N2-SUCCINYLGLUTAMATE GLT SUC)
 (PWY LCYSDEG-PWY (CYS WATER) HS AMMONIA PYRUVATE)
 (PWY GLUTAMINDEG-PWY (GLN WATER) AMMONIA GLT)
 (PWY GLYCLEAV-PWY (THF GLY NAD) PROTON NADH PROTEIN-LIPOYLLYSINE
  AMINOMETHYLDIHYDROLIPOYL-GCVH CARBON-DIOXIDE METHYLENE-THF AMMONIA
  DIHYDROLIPOYL-GCVH)
 (PWY PWY0-461 (LYS) CADAVERINE CARBON-DIOXIDE)
 (PWY PWY0-981 (TAURINE 2-KETOGLUTARATE OXYGEN-MOLECULE) CARBON-DIOXIDE
  SUC SO3 CPD-1772)
 (PWY PROUT-PWY (NAD WATER PRO FAD) FADH2
  |l-delta(1)-pyrroline_5-carboxylate| NADH GLT)
 (PWY SERDEG-PWY (SER) AMMONIA PYRUVATE)
 (PWY PWY-5436 (NAD CO-A THR) GLY ACETALD ACETYL-COA NADH)
 (PWY PWY-5437 (ADP |Pi| THR) AMMONIA 2-OXOBUTANOATE FORMATE
  PROPIONYL-COA CO-A PROPIONYL-P PROPIONATE ATP)
 (PWY THRDLCTCAT-PWY (WATER OXYGEN-MOLECULE THR NAD) NADH AMINO-OXOBUT
  CARBON-DIOXIDE AMINO-ACETONE HYDROGEN-PEROXIDE AMMONIA
  METHYL-GLYOXAL)
 (PWY THREONINE-DEG2-PWY (CO-A THR NAD) NADH AMINO-OXOBUT ACETYL-COA
  GLY)
 (PWY TRYPDEG-PWY (TRP WATER) AMMONIA PYRUVATE INDOLE)
 (PWY HCAMHPDEG-PWY
  (OXYGEN-MOLECULE 3-PHENYLPROPIONATE PROTON
   3-HYDROXYPHENYL-PROPIONATE)
  SUC OXOPENTENOATE WATER NADH 2-3-DIHYDROXYPHENYL-PROPIONATE NAD
  CARBOXYETHYL-3-5-CYCLOHEXADIENE-1-2-DIOL CPD-157)
 (PWY PWY0-321 (OXYGEN-MOLECULE WATER CO-A PHENYLACETATE ATP) PPI AMP
  CPD-207 SUC-COA E- 3-KETO-ADIPYL-COA 3-HYDROXYADIPYL-COA PROTON
  ACETYL-COA CIS-DIHYDRODIOL-DERIV-PHEAC)
 (PWY PWY-1801 (|NAD(P)| FORMALDEHYDE WATER) GLUTATHIONE FORMATE
  S-HYDROXYMETHYLGLUTATHIONE PROTON |NAD(P)H| CPD-548)
 (PWY PWY-5162 (NAD CO-A OXOPENTENOATE WATER) 4-HYDROXY-2-KETOVALERATE
  PYRUVATE ACETALD ACETYL-COA NADH)
 (PWY PWY0-1309 (ATP DIACETYLCHITOBIOSE-6-PHOSPHATE WATER)
  N-ACETYL-D-GLUCOSAMINE ADP N-ACETYL-D-GLUCOSAMINE-6-P)
 (PWY FUCCAT-PWY (L-FUCOSE ATP) DIHYDROXY-ACETONE-PHOSPHATE LACTALD ADP
  FUCULOSE-1P L-FUCULOSE)
 (PWY GLUCOSE1PMETAB-PWY (GLC ATP GLC-1-P WATER |Ubiquinones|)
  |Ubiquinols| GLC-D-LACTONE |D-Glucose| |Pi| ALPHA-GLC-6-P ADP
  GLC-6-P)
 (PWY LYXMET-PWY (ATP L-LYXOSE) L-XYLULOSE ADP L-XYLULOSE-5-P
  L-RIBULOSE-5-P XYLULOSE-5-PHOSPHATE)
 (PWY MANNCAT-PWY (MANNOSE ATP) FRUCTOSE-6P ADP MANNOSE-6P)
 (PWY PWY0-1300 (ATP CPD0-1063 WATER) GLYCERATE MANNOSE-6P ADP 2-PG)
 (PWY PWY0-1301 (WATER MELIBIOSE) GALACTOSE GLC)
 (PWY PWY0-1314 (ATP FRU1P) FRUCTOSE-16-DIPHOSPHATE ADP)
 (PWY PWY0-44 (ALLOSE ATP) D-ALLULOSE-6-PHOSPHATE FRUCTOSE-6P ADP
  D-ALLOSE-6-PHOSPHATE)
 (PWY RHAMCAT-PWY (RHAMNOSE ATP) DIHYDROXY-ACETONE-PHOSPHATE LACTALD
  ADP RHAMNULOSE-1P RHAMNULOSE)
 (PWY RIBOKIN-PWY (CPD0-1110 ATP) ADP RIBOSE-5P RIBOSE CPD0-1108)
 (PWY DARABCATK12-PWY (WATER NAD ATP D-ARABINOSE) RIBULOSE ADP
  D-RIBULOSE-1-P DIHYDROXY-ACETONE-PHOSPHATE GLYCOLALDEHYDE GLYCOLLATE
  NADH)
 (PWY ARABCAT-PWY (ATP L-ARABINOSE) L-RIBULOSE XYLULOSE-5-PHOSPHATE ADP
  L-RIBULOSE-5-P)
 (PWY BGALACT-PWY (WATER LACTOSE) GLC GALACTOSE)
 (PWY PWY0-1182 (ATP TREHALOSE WATER) GLC ADP GLC-6-P)
 (PWY TREDEGLOW-PWY (ATP TREHALOSE-6P WATER) GLC ADP GLC-6-P)
 (PWY XYLCAT-PWY (XYLOSE ATP) ADP XYLULOSE-5-PHOSPHATE D-XYLULOSE)
 (PWY GLYCOLATEMET-PWY (NADH PROTON |Acceptor| GLYCOLLATE ATP) ADP G3P
  TARTRONATE-S-ALD CARBON-DIOXIDE GLYOX |Donor-H2| NAD GLYCERATE)
 (PWY GLYOXDEG-PWY (|Acceptor| GLYCOLLATE ACETYL-COA WATER) CO-A MAL
  GLYOX |Donor-H2|)
 (PWY PWY0-1313 (CO-A ACET ATP) AMP PPI ACETYL-COA)
 (PWY PWY0-301 (L-ASCORBATE-6-PHOSPHATE WATER) L-RIBULOSE-5-P
  CARBON-DIOXIDE L-XYLULOSE-5-P XYLULOSE-5-PHOSPHATE CPD-2343)
 (PWY PYRUVDEHYD-PWY (NAD CO-A PYRUVATE) CARBON-DIOXIDE
  |Pyruvate-dehydrogenase-acetylDHlipoyl|
  |Pyruvate-dehydrogenase-dihydrolipoate| ACETYL-COA PROTON NADH
  |Pyruvate-dehydrogenase-lipoate|)
 (PWY PWY0-1312 (|Pi| ACETYL-COA ADP) ATP ACET CO-A ACETYL-P)
 (PWY PROPIONMET-PWY (ATP HCO3 PROPIONYL-COA) METHYL-MALONYL-COA
  SUC-COA D-METHYL-MALONYL-COA |Pi| ADP)
 (PWY PWY0-42 (OXALACETIC_ACID PROPIONATE ATP) AMP PPI PROPIONYL-COA
  CO-A CPD-622 CPD-1136 WATER CPD-618 PYRUVATE SUC)
 (PWY PWY0-43 (SUC) METHYL-MALONYL-COA CARBON-DIOXIDE PROPIONYL-COA
  SUC-COA PROPIONATE)
 (PWY ACETOACETATE-DEG-PWY (3-KETOBUTYRATE CO-A) ACETYL-COA ACET
  ACETOACETYL-COA)
 (PWY FAO-PWY
  (WATER CIS-DELTA3-ENOYL-COA FAD CO-A |a fatty acid| ATP
   D-3-HYDROXYACYL-COA NAD)
  3-KETOACYL-COA NADH ACETYL-COA AMP PPI ACYL-COA D2-ENOYL-COA FADH2
  TRANS-D2-ENOYL-COA L-3-HYDROXYACYL-COA)
 (PWY CYANCAT-PWY (CPD-69 WATER) AMMONIA PROTON HCO3 CARBON-DIOXIDE
  CARBAMATE)
 (PWY ALKANEMONOX-PWY
  (|Alkanesulfonates| OXYGEN-MOLECULE |NAD(P)H| PROTON) |NAD(P)| FMNH2
  FMN WATER SO3 |an aldehyde|)
 (PWY SO4ASSIM-PWY (SULFATE ATP NADPH |Red-Thioredoxin|)
  |Ox-Thioredoxin| SO3 PAP HS NADP WATER ADP PAPS PPI APS)
 (PWY PWY0-1295 (|Pi| WATER CYTIDINE) URIDINE AMMONIA URACIL RIBOSE-1P
  RIBOSE-5P)
 (PWY PWY0-1296 (GUANOSINE |Pi| WATER ADENOSINE XANTHOSINE) XANTHINE
  ADENINE INOSINE AMMONIA HYPOXANTHINE RIBOSE-5P GUANINE RIBOSE-1P)
 (PWY PWY0-1297 (NAD CO-A WATER DEOXYADENOSINE |Pi| DEOXYGUANOSINE)
  GUANINE ADENINE DEOXY-RIBOSE-1P HYPOXANTHINE DEOXYINOSINE AMMONIA
  DEOXY-RIBOSE-5P GAP ACETALD ACETYL-COA NADH)
 (PWY PWY0-1298 (NAD CO-A THYMIDINE |Pi| WATER DEOXYCYTIDINE)
  DEOXYURIDINE AMMONIA URACIL THYMINE DEOXY-RIBOSE-1P DEOXY-RIBOSE-5P
  GAP ACETALD ACETYL-COA NADH)
 (PWY DETOX1-PWY (PROTON SUPER-OXIDE) HYDROGEN-PEROXIDE OXYGEN-MOLECULE
  WATER)
 (PWY PWY0-1261 (CPD0-882 ATP) D-LACTATE N-ACETYL-D-GLUCOSAMINE-6-P ADP
  CPD0-881)
 (PWY PWY0-521 (PSICOSELYSINE ATP WATER) LYS GLC-6-P ADP
  FRUCTOSELYSINE-6-PHOSPHATE FRUCTOSELYSINE)
 (PWY GALACTARDEG-PWY (ATP D-GALACTARATE |NAD(P)H| PROTON)
  TARTRONATE-S-ALD PYRUVATE |NAD(P)| GLYCERATE WATER
  5-KETO-4-DEOXY-D-GLUCARATE ADP 2-PG)
 (PWY GALACTCAT-PWY (D-GALACTONATE ATP) ADP
  DEHYDRO-DEOXY-GALACTONATE-PHOSPHATE PYRUVATE GAP
  2-DEHYDRO-3-DEOXY-D-GALACTONATE WATER)
 (PWY GALACTUROCAT-PWY (D-GALACTURONATE NADH ATP)
  2-DEHYDRO-3-DEOXY-D-GLUCONATE WATER ADP 2-KETO-3-DEOXY-6-P-GLUCONATE
  D-ALTRONATE NAD D-TAGATURONATE)
 (PWY GLUCARDEG-PWY (ATP D-GLUCARATE |NAD(P)H| PROTON) TARTRONATE-S-ALD
  PYRUVATE |NAD(P)| GLYCERATE WATER 5-KETO-4-DEOXY-D-GLUCARATE ADP
  2-PG)
 (PWY GLUCUROCAT-PWY (|Beta-D-Glucuronides| NADH ATP)
  2-DEHYDRO-3-DEOXY-D-GLUCONATE WATER ADP 2-KETO-3-DEOXY-6-P-GLUCONATE
  D-MANNONATE NAD FRUCTURONATE GLUCURONATE |Alcohols|)
 (PWY IDNCAT-PWY (L-IDONATE ATP) GLUCONATE |NAD(P)| CPD-2961 ADP
  5-DEHYDROGLUCONATE |NAD(P)H|)
 (PWY PWY0-1306 (ATP CPD0-1083) NADH D-TAGATURONATE D-ALTRONATE NAD
  2-DEHYDRO-3-DEOXY-D-GLUCONATE WATER ADP 2-KETO-3-DEOXY-6-P-GLUCONATE)
 (PWY GALACTITOLCAT-PWY (GALACTITOL-1-PHOSPHATE NAD ATP) ADP
  TAGATOSE-1-6-DIPHOSPHATE GAP DIHYDROXY-ACETONE-PHOSPHATE NADH
  TAGATOSE-6-PHOSPHATE)
 (PWY MANNIDEG-PWY (MANNITOL-1P NAD) NADH FRUCTOSE-6P)
 (PWY SORBDEG-PWY (D-SORBITOL-6-P NAD) NADH FRUCTOSE-6P)
 (PWY PWY0-1299 (ARG) AGMATHINE CARBON-DIOXIDE)
 (PWY PWY0-1305 (GLT) 4-AMINO-BUTYRATE CARBON-DIOXIDE)
 (PWY ENTNER-DOUDOROFF-PWY (CPD-2961) PYRUVATE GAP WATER
  2-KETO-3-DEOXY-6-P-GLUCONATE)
 (PWY FERMENTATION-PWY
  (|Menaquinols| PROTON UBIQUINONE-8 PHOSPHO-ENOL-PYRUVATE NADH ADP)
  ACETYL-P ACETYL-COA FORMATE ACETALD CO-A ETOH ATP PYRUVATE D-LACTATE
  WATER FUM NAD MAL |Pi| OXALACETIC_ACID HYDROGEN-MOLECULE UBIQUINOL-8
  CARBON-DIOXIDE ACET |Menaquinones| SUC)
 (PWY GLYCOLYSIS (GLC-6-P NAD) PYRUVATE WATER 2-PG ATP G3P NADH DPG GAP
  DIHYDROXY-ACETONE-PHOSPHATE FRUCTOSE-16-DIPHOSPHATE ADP AMP
  PHOSPHO-ENOL-PYRUVATE |Pi| FRUCTOSE-6P)
 (PWY NONOXIPENT-PWY (RIBULOSE-5P) ERYTHROSE-4P FRUCTOSE-6P GAP
  D-SEDOHEPTULOSE-7-P XYLULOSE-5-PHOSPHATE RIBOSE-5P)
 (PWY OXIDATIVEPENT-PWY (GLC-6-P NADP |NAD(P)| WATER) CPD-2961
  |NAD(P)H| CARBON-DIOXIDE RIBULOSE-5P PROTON NADPH
  D-6-P-GLUCONO-DELTA-LACTONE)
 (PWY AERESPDON-PWY
  (PROTON |Ubiquinones| NADH |Acceptor| L-LACTATE D-LACTATE
   |Unknown-Quinones| SUC GLYCEROL-3P UBIQUINONE-8)
  UBIQUINOL-8 DIHYDROXY-ACETONE-PHOSPHATE FUM |Unknown-Quinols|
  PYRUVATE |Donor-H2| NAD |Ubiquinols|)
 (PWY ANA-ELECT-TRANS-PWY (|Acceptor| |NAD(P)H|)
  |Red-FMNH2-Flavoproteins| |Red-FADH2-Flavoproteins| |NAD(P)|
  |Ox-FAD-Flavoproteins| |FeS-Proteins-Reduced| |Ox-FMN-Flavoproteins|
  |Red-Menaquinol-8-Oxidoreductases| |FeS-Proteins|
  |Red-Demethylmenaquinol-Oxidoreductases| PROTON
  |Ox-Menaquinone-8-Oxidoreductases|
  |Ox-Demethylmenaquinone-Oxidoreductases| |Cytochromes-B-Reduced|
  |Cytochromes-B| |Donor-H2|)
 (PWY ANARESP1-PWY (|Menaquinols| PROTON 2-PG NADP ADP) ATP PYRUVATE
  NADH CO-A CIT CIS-ACONITATE |threo-d(s)-iso-citrate| 2-KETOGLUTARATE
  NADPH |Pi| OXALACETIC_ACID NAD MAL FUM ACETYL-COA FORMATE WATER
  PHOSPHO-ENOL-PYRUVATE HYDROGEN-MOLECULE CARBON-DIOXIDE |Menaquinones|
  SUC)
 (PWY ANARESPACC-PWY
  (|Cytochromes-C552-Red| PROTON FUM |Menaquinols| TRIMENTHLAMINE-N-O
   |Cytochromes-C-Reduced| UBIQUINOL-10 NITRATE NADH
   TETRAHYDROTHIOPHENE-1-OXIDE |Donor-H2| DMSO)
  CPD-7670 |Acceptor| TETRAHYDROTHIOPHENE NAD AMMONIUM OH NITRITE
  UBIQUINONE-10 |Cytochromes-C| TRIMETHYLAMINE |Menaquinones| SUC WATER
  |Cytochromes-C552-Ox| AMMONIA)
 (PWY ANARESPDON-PWY
  (HYDROGEN-MOLECULE |Acceptor| |Ubiquinones| NADH FORMATE
   |Menaquinones| L-LACTATE GLYCEROL-3P UBIQUINONE-8)
  UBIQUINOL-8 DIHYDROXY-ACETONE-PHOSPHATE PYRUVATE |Menaquinols|
  CARBON-DIOXIDE NAD |Ubiquinols| |Donor-H2| PROTON)
 (PWY GLYOXYLATE-BYPASS (ACETYL-COA NAD) NADH OXALACETIC_ACID MAL SUC
  GLYOX |threo-d(s)-iso-citrate| CO-A CIT WATER CIS-ACONITATE)
 (PWY TCA (|Acceptor| |Ubiquinones| ACETYL-COA NADP NAD ADP |Pi|) MAL
  ATP SUC NADH SUC-COA CARBON-DIOXIDE 2-KETOGLUTARATE NADPH
  |threo-d(s)-iso-citrate| CO-A CIT WATER CIS-ACONITATE FUM
  |Ubiquinols| OXALACETIC_ACID |Donor-H2|))


((PWY-CATALYZE GLUTORN-PWY N-ACETYLTRANSFER-CPLX ACETYLGLUTKIN-CPLX
  N-ACETYLGLUTPREDUCT-MONOMER ACETYLORNTRANSAM-CPLX SUCCORNTRANSAM-CPLX
  ACETYLORNDEACET-CPLX)
 (PWY-CATALYZE PWY0-901 EG10943-MONOMER CPLX0-1141 SERS-CPLX)
 (PWY-CATALYZE ALANINE-SYN2-PWY MONOMER0-1241)
 (PWY-CATALYZE ALANINE-VALINESYN-PWY BRANCHED-CHAINAMINOTRANSFER-CPLX
  ALARACEBIOSYN-MONOMER CPLX0-7465
  VALINE-PYRUVATE-AMINOTRANSFER-MONOMER)
 (PWY-CATALYZE PWY0-1021 CPLX0-248)
 (PWY-CATALYZE ASPARAGINESYN-PWY ASNSYNA-CPLX ASNSYNB-CPLX)
 (PWY-CATALYZE ASPARTATESYN-PWY ASPAMINOTRANS-DIMER)
 (PWY-CATALYZE GLUTDEG-PWY ASPAMINOTRANS-DIMER ASPARTASE-CPLX)
 (PWY-CATALYZE PWY-5155 CPLX0-2901)
 (PWY-CATALYZE CYSTSYN-PWY CPLX0-237 ACSERLYA-CPLX)
 (PWY-CATALYZE GLUTSYN-PWY GLUTAMATESYN-CPLX)
 (PWY-CATALYZE GLUTSYNIII-PWY GDHA-CPLX)
 (PWY-CATALYZE GLNSYN-PWY GLUTAMINESYN-OLIGOMER)
 (PWY-CATALYZE GLYSYN-PWY GLYOHMETRANS-CPLX)
 (PWY-CATALYZE HISTSYN-PWY HISTDEHYD-CPLX HISTPHOSTRANS-CPLX
  IMIDHISTID-CPLX GLUTAMIDOTRANS-CPLX PRIBFAICARPISOM-MONOMER
  HISTCYCLOPRATPPHOS CPLX0-7614)
 (PWY-CATALYZE ILEUSYN-PWY DIHYDROXYACIDDEHYDRAT-CPLX
  BRANCHED-CHAINAMINOTRANSFER-CPLX CPLX0-7643 ACETOLACTSYNIII-CPLX
  ACETOLACTSYNI-CPLX ACETOLACTSYNII-CPLX THREDEHYDSYN-CPLX)
 (PWY-CATALYZE LEUSYN-PWY 3-ISOPROPYLMALDEHYDROG-CPLX
  BRANCHED-CHAINAMINOTRANSFER-CPLX TYRB-DIMER
  2-ISOPROPYLMALATESYN-MONOMER 3-ISOPROPYLMALISOM-CPLX)
 (PWY-CATALYZE DAPLYSINESYN-PWY DIAMINOPIMEPIM-MONOMER
  DIAMINOPIMDECARB-CPLX CPLX0-3161 ACETYLORNTRANSAM-CPLX CPLX0-3181
  DIHYDROPICRED-CPLX DIHYDRODIPICSYN-CPLX
  ASP-SEMIALDEHYDE-DEHYDROGENASE-CPLX ASPKINIHOMOSERDEHYDROGI-CPLX
  ASPKINIIHOMOSERDEHYDROGII-CPLX ASPKINIII-CPLX)
 (PWY-CATALYZE HOMOSER-METSYN-PWY HOMSUCTRAN-CPLX HOMOCYSMET-MONOMER
  HOMOCYSMETB12-MONOMER CYSTATHIONINE-BETA-LYASE-CPLX EG10564-MONOMER
  O-SUCCHOMOSERLYASE-CPLX)
 (PWY-CATALYZE HOMOSERSYN-PWY ASPKINIII-CPLX
  ASP-SEMIALDEHYDE-DEHYDROGENASE-CPLX ASPKINIHOMOSERDEHYDROGI-CPLX
  ASPKINIIHOMOSERDEHYDROGII-CPLX)
 (PWY-CATALYZE PHESYN TYRB-DIMER ASPAMINOTRANS-DIMER
  CHORISMUTPREPHENDEHYDRAT-CPLX CHORISMUTPREPHENDEHYDROG-CPLX)
 (PWY-CATALYZE PROSYN-PWY PYRROLINECARBREDUCT-CPLX
  GLUTSEMIALDEHYDROG-CPLX GLUTKIN-CPLX GDHA-CPLX GLUTAMATESYN-CPLX)
 (PWY-CATALYZE SERSYN-PWY PSERTRANSAM-CPLX PGLYCDEHYDROG-CPLX
  PSERPHOSPHA-MONOMER)
 (PWY-CATALYZE HOMOSER-THRESYN-PWY HOMOSERKIN-CPLX THRESYN-MONOMER)
 (PWY-CATALYZE TRPSYN-PWY PRAI-IGPS ANTHRANSYNCOMPII ANTHRANSYN-CPLX
  TRYPSYN-APROTEIN CPLX0-2401)
 (PWY-CATALYZE TYRSYN TYRB-DIMER CHORISMUTPREPHENDEHYDRAT-CPLX
  CHORISMUTPREPHENDEHYDROG-CPLX)
 (PWY-CATALYZE VALSYN-PWY DIHYDROXYACIDDEHYDRAT-CPLX
  BRANCHED-CHAINAMINOTRANSFER-CPLX CPLX0-7643 ACETOLACTSYNI-CPLX
  ACETOLACTSYNII-CPLX ACETOLACTSYNIII-CPLX)
 (PWY-CATALYZE TRNA-CHARGING-PWY ARGS-MONOMER CYSS-MONOMER GLNS-MONOMER
  GLURS-MONOMER ILES-MONOMER LEUS-MONOMER VALS-MONOMER ALAS-CPLX
  ASNS-CPLX ASPS-CPLX TYRS-CPLX TRPS-CPLX THRS-CPLX SERS-CPLX PROS-CPLX
  PHES-CPLX METG-CPLX LYSU-CPLX LYSS-CPLX HISS-CPLX GLYS-CPLX)
 (PWY-CATALYZE GLUCONEO-PWY PGLUCISOM F16B-CPLX CPLX0-303
  EG11239-MONOMER FRUCBISALD-CLASSII FRUCBISALD-CLASSI GAPDH-A-CPLX PGK
  PHOSGLYCMUTASE PGAM2-MONOMER PGMI-MONOMER ENOLASE-CPLX
  PEPCARBOXYKIN-MONOMER MALATE-DEHASE PEPSYNTH-CPLX MALIC-NAD-CPLX
  MALIC-NADP-CPLX PEPCARBOX-CPLX)
 (PWY-CATALYZE GLYCOCAT-PWY AMYLOMALT-MONOMER GLYCOPHOSPHORYL-CPLX
  PHOSPHOGLUCMUT-MONOMER EG10381-MONOMER MALDEXPHOSPHORYL-CPLX
  MALTODEXGLUCOSID-MONOMER GLUCOKIN-MONOMER)
 (PWY-CATALYZE GALACTMETAB-PWY GALACTOKIN-MONOMER
  GALACTURIDYLYLTRANS-CPLX UDPGLUCEPIM-CPLX GLUC1PURIDYLTRANS-CPLX)
 (PWY-CATALYZE PWY-1269 CPM-KDOSYNTH-MONOMER KDO-8PPHOSPHAT-CPLX
  KDO-8PSYNTH-CPLX CPLX0-1262 CPLX0-3929)
 (PWY-CATALYZE PWY0-1241 CPLX0-3661 EG11736-MONOMER CPLX0-3681
  CPLX0-7660)
 (PWY-CATALYZE DTDPRHAMSYN-PWY DTDPDEHYDRHAMEPIM-MONOMER
  DTDPDEHYRHAMREDUCT-MONOMER DTDPGLUCDEHYDRAT-CPLX
  DTDPGLUCOSEPP-MONOMER)
 (PWY-CATALYZE TRESYN-PWY TREHALOSE6PSYN-MONOMER
  TREHALOSEPHOSPHASYN-MONOMER)
 (PWY-CATALYZE GLYCOGENSYNTH-PWY GLYCOGENSYN-CPLX
  GLYCOGEN-BRANCH-MONOMER GLUC1PADENYLTRANS-CPLX)
 (PWY-CATALYZE COLANSYN-PWY MANNPISOM-MONOMER PHOSMANMUT-MONOMER
  MANNPGUANYLTRANGDP-MONOMER GDPMANDEHYDRA-CPLX GALACTOKIN-MONOMER
  GALACTURIDYLYLTRANS-CPLX UDPGLUCEPIM-CPLX GLUC1PURIDYLTRANS-CPLX
  UGD-MONOMER CPLX0-3881)
 (PWY-CATALYZE ECASYN-PWY GLCNACPTRANS-MONOMER UDPMANACATRANS-MONOMER
  UDPMANNACADEHYDROG-MONOMER G7800-MONOMER TDPFUCACTRANS-MONOMER
  UDPGLCNACEPIM-MONOMER RFFTRANS-MONOMER DTDPGLUCOSEPP2-MONOMER
  DTDPGLUCDEHYDRAT2-MONOMER)
 (PWY-CATALYZE KDOSYN-PWY KDOTRANS-MONOMER)
 (PWY-CATALYZE MANGDPMET-PWY GDPMANMANHYDRO-MONOMER MANNKIN-MONOMER
  MANNPGUANYLTRANGDP-MONOMER PHOSMANMUT-MONOMER MANNPISOM-MONOMER)
 (PWY-CATALYZE NAGLIPASYN-PWY CPLX0-7415 TETRAACYLDISACC4KIN-MONOMER
  EG12666-MONOMER UDPHYDROXYMYRGLUCOSAMNACETYLTRANS-MONO
  UDPACYLGLCNACDEACETYL-MONOMER UDPNACETYLGLUCOSAMACYLTRANS-CPLX)
 (PWY-CATALYZE UDPNAGSYN-PWY NAG1P-URIDYLTRANS-CPLX
  L-GLN-FRUCT-6-P-AMINOTRANS-CPLX PHOSGLUCOSAMINEMUT-MONOMER)
 (PWY-CATALYZE PEPTIDOGLYCANSYN-PWY
  UDPNACETYLGLUCOSAMENOLPYRTRANS-MONOMER
  UDPNACETYLMURAMATEDEHYDROG-MONOMER NACGLCTRANS-MONOMER
  UDP-NACMURALGLDAPAALIG-MONOMER UDP-NACMUR-ALA-LIG-MONOMER
  UDP-NACMURALA-GLU-LIG-MONOMER GLUTRACE-CPLX
  UDP-NACMURALGLDAPLIG-MONOMER DALADALALIGA-MONOMER DALADALALIGB-CPLX
  PHOSNACMURPENTATRANS-MONOMER)
 (PWY-CATALYZE NONMEVIPP-PWY CPLX0-743 DXPREDISOM-CPLX EG10370-MONOMER
  CPLX0-7564 CPLX0-234 CPLX0-3841 CPLX0-721 IPPISOM-MONOMER)
 (PWY-CATALYZE PWY-5123 FPPSYN-MONOMER IPPISOM-MONOMER)
 (PWY-CATALYZE SAM-PWY S-ADENMETSYN-CPLX ADOMETSYN2-CPLX)
 (PWY-CATALYZE COA-PWY COADTRI-CPLX EG12312-MONOMER CPLX0-341
  PANTOTHENATE-KIN-CPLX)
 (PWY-CATALYZE P2-PWY G6340-MONOMER G6339-MONOMER)
 (PWY-CATALYZE PWY0-1275 EG11796-MONOMER CPLX0-782)
 (PWY-CATALYZE PWY0-501 CPLX0-782 EG11591-MONOMER AAS-MONOMER)
 (PWY-CATALYZE PWY0-522 EG11796-MONOMER)
 (PWY-CATALYZE NADPHOS-DEPHOS-PWY PYRNUTRANSHYDROGEN-CPLX CPLX0-682
  6PFK-1-MONOMER NADPPHOSPHAT-MONOMER)
 (PWY-CATALYZE PYRIDNUCSAL-PWY NICONUCADENYLYLTRAN-MONOMER
  NMNAMIDOHYDRO-MONOMER EG11702-MONOMER NICOTINATEPRIBOSYLTRANS-MONOMER
  NICOTINAMID-MONOMER NADNUCLEOSID-MONOMER NMNNUCLEOSID-MONOMER
  NAD-SYNTH-CPLX)
 (PWY-CATALYZE PYRIDNUCSYN-PWY NICONUCADENYLYLTRAN-MONOMER
  NAD-SYNTH-CPLX QUINOPRIBOTRANS-CPLX QUINOLINATE-SYNTHA-MONOMER
  L-ASPARTATE-OXID-MONOMER)
 (PWY-CATALYZE PWY-5783 CPLX0-7426) (PWY-CATALYZE PWY-5785 UPPSYN-CPLX)
 (PWY-CATALYZE PWY-5194 SIROHEMESYN-CPLX)
 (PWY-CATALYZE HEMESYN2-PWY PROTOPORGENOXI-MONOMER
  PROTOHEME-FERROCHELAT-MONOMER UROGENDECARBOX-MONOMER HEMN-MONOMER
  COPROGENOXI-MONOMER)
 (PWY-CATALYZE MENAQUINONESYN-PWY DMK-MONOMER
  2-OCTAPRENYL-METHOXY-BENZOQ-METH-MONOMER NAPHTHOATE-SYN-MONOMER
  MENE-CPLX O-SUCCINYLBENZOATE-COA-SYN-MONOMER MENF-CPLX CPLX0-7525)
 (PWY-CATALYZE UBISYN-PWY OCTAPRENYL-METHYL-METHOXY-BENZOQ-OH-MON
  2-OCTAPRENYL-METHOXY-BENZOQ-METH-MONOMER
  OCTAPRENYL-METHOXYPHENOL-OH-MONOMER DHHB-METHYLTRANSFER-CPLX
  2-OCTAPRENYLPHENOL-HYDROX-MONOMER CPLX0-301 UBIX-MONOMER
  4OHBENZOATE-OCTAPRENYLTRANSFER-MONOMER CHORPYRLY-MONOMER)
 (PWY-CATALYZE GLUT-REDOX-PWY PRODISULFREDUCT-MONOMER
  GLUTATHIONE-REDUCT-NADPH-CPLX)
 (PWY-CATALYZE GLUTATHIONESYN-PWY GLUTCYSLIG-MONOMER
  GLUTATHIONE-SYN-CPLX)
 (PWY-CATALYZE THIOREDOX-PWY THIOREDOXIN-REDUCT-NADPH-CPLX)
 (PWY-CATALYZE PWY-5188 UROGENIIISYN-MONOMER OHMETHYLBILANESYN-MONOMER
  PORPHOBILSYNTH-CPLX GSAAMINOTRANS-CPLX CPLX0-3741 GLURS-MONOMER)
 (PWY-CATALYZE RIBOSYN2-PWY RIBF-MONOMER CPLX0-3952 LUMAZINESYN-CPLX
  RIBOPHOSPHAT-MONOMER DIOHBUTANONEPSYN-CPLX CPLX0-7659
  GTP-CYCLOHYDRO-II-CPLX)
 (PWY-CATALYZE BIOTIN-SYNTHESIS-PWY DETHIOBIOTIN-SYN-CPLX
  BIOTIN-SYN-CPLX DAPASYN-CPLX 7KAPSYN-CPLX)
 (PWY-CATALYZE PWY-5448 THREODEHYD-CPLX GLYCDEH-CPLX)
 (PWY-CATALYZE COBALSYN-PWY COBS-MONOMER RIBAZOLEPHOSPHAT-MONOMER
  COBU-CPLX DMBPPRIBOSYLTRANS-CPLX COBALADENOSYLTRANS-MONOMER)
 (PWY-CATALYZE 1CMET2-PWY MONOMER0-1661 FORMATETHFLIG-MONOMER
  FORMYLTHFDEFORMYL-CPLX DIHYDROFOLATEREDUCT-MONOMER G6862-MONOMER
  GLYOHMETRANS-CPLX FOLD-CPLX GCVMULTI-CPLX METHYLENETHFREDUCT-CPLX
  HOMOCYSMETB12-MONOMER THYMIDYLATESYN-CPLX FOLC-MONOMER)
 (PWY-CATALYZE FOLSYN-PWY ADCLY-CPLX H2PTEROATESYNTH-CPLX PABASYN-CPLX
  FOLD-CPLX FOLC-MONOMER DIHYDROFOLATEREDUCT-MONOMER G6862-MONOMER
  H2PTERIDINEPYROPHOSPHOKIN-MONOMER CPLX0-3936
  DIHYDRONEOPTERIN-MONO-P-DEPHOS-MONOMER
  H2NEOPTERINP3PYROPHOSPHOHYDRO-MONOMER FOLE-CPLX GART-MONOMER)
 (PWY-CATALYZE PWY-2161 FORMATETHFLIG-MONOMER GLYOHMETRANS-CPLX
  FOLC-MONOMER MONOMER0-1661)
 (PWY-CATALYZE PANTO-PWY PANTOATE-BETA-ALANINE-LIG-CPLX
  2-DEHYDROPANTOATE-REDUCT-MONOMER 3-METHYL-2-OXOBUT-OHCH3XFER-CPLX
  BRANCHED-CHAINAMINOTRANSFER-CPLX)
 (PWY-CATALYZE PLPSAL-PWY PDXH-CPLX PDXK-CPLX PDXY-MONOMER)
 (PWY-CATALYZE PYRIDOXSYN-PWY PDXH-CPLX ERYTH4PDEHYDROG-CPLX CPLX0-743
  CPLX0-321 ERYTHRON4PDEHYDROG-MONOMER PSERTRANSAM-CPLX PDXA-MONOMER)
 (PWY-CATALYZE KDO-LIPASYN-PWY LAUROYLACYLTRAN-MONOMER
  MYRISTOYLACYLTRAN-MONOMER)
 (PWY-CATALYZE LIPA-CORESYN-PWY EG11189-MONOMER EG12210-MONOMER
  EG11339-MONOMER EG11340-MONOMER EG11341-MONOMER EG11425-MONOMER
  EG11351-MONOMER EG11352-MONOMER EG11353-MONOMER EG11423-MONOMER)
 (PWY-CATALYZE PWY0-1264 BIOTINLIG-MONOMER BIOTIN-CARBOXYL-CPLX
  ACETYL-COA-CARBOXYLTRANSFER-CPLX)
 (PWY-CATALYZE FASYN-ELONG-PWY FABA-CPLX FABZ-CPLX
  ENOYL-ACP-REDUCT-NADH-MONOMER 3-OXOACYL-ACP-REDUCT-MONOMER FABB-CPLX
  3-OXOACYL-ACP-SYNTHII-CPLX)
 (PWY-CATALYZE FASYN-INITIAL-PWY 3-OXOACYL-ACP-SYNTHII-CPLX
  MALONYL-COA-ACP-TRANSACYL-MONOMER FABB-CPLX CPLX0-252
  ACETYL-COA-CARBOXYLMULTI-CPLX)
 (PWY-CATALYZE PWY0-862 ENOYL-ACP-REDUCT-NADH-MONOMER
  3-OXOACYL-ACP-REDUCT-MONOMER FABB-CPLX FABZ-CPLX FABA-CPLX)
 (PWY-CATALYZE PWY0-541 CFA-CPLX)
 (PWY-CATALYZE PWY-5667 CDPDIGLYSYN-MONOMER
  1-ACYLGLYCEROL-3-P-ACYLTRANSFER-MONOMER
  GLYCEROL-3-P-ACYLTRANSFER-MONOMER GLYC3PDEHYDROGBIOSYN-CPLX)
 (PWY-CATALYZE PWY-5669 PHOSPHASERSYN-CPLX PHOSPHASERDECARB-CPLX)
 (PWY-CATALYZE PWY0-1319 CDPDIGLYSYN-MONOMER GLYC3PDEHYDROGBIOSYN-CPLX
  GLYCEROL-3-P-ACYLTRANSFER-MONOMER
  1-ACYLGLYCEROL-3-P-ACYLTRANSFER-MONOMER)
 (PWY-CATALYZE PWY-5668 PGPPHOSPHAA-MONOMER PGPPHOSPHAB-MONOMER
  PGPPHOSPHAC-MONOMER CARDIOLIPSYN-MONOMER G6406-MONOMER
  PHOSPHAGLYPSYN-MONOMER)
 (PWY-CATALYZE PPGPPMET-PWY PPPGPPHYDRO-CPLX SPOT-MONOMER RELA-MONOMER)
 (PWY-CATALYZE DENOVOPURINE2-PWY PRPPAMIDOTRANS-CPLX
  GLYCRIBONUCSYN-MONOMER GART-MONOMER GARTRANSFORMYL2-MONOMER
  FGAMSYN-MONOMER AIRS-CPLX SAICARSYN-CPLX AICARTRANSIMPCYCLO-CPLX
  ADENYLOSUCCINATE-SYN-DIMER ASL-MONOMER ADENYL-KIN-MONOMER
  IMP-DEHYDROG-CPLX GMP-SYN-CPLX GUANYL-KIN-CPLX
  RIBONUCLEOSIDE-DIP-REDUCTI-CPLX PURE-CPLX PURK-CPLX
  RIBONUCLEOSIDE-TRIP-REDUCT-CPLX RIBONUCLEOSIDE-DIP-REDUCTII-CPLX
  NUCLEOSIDE-DIP-KIN-CPLX)
 (PWY-CATALYZE SALVADEHYPOX-PWY AMP-NUCLEOSID-CPLX
  ADENPRIBOSYLTRAN-CPLX DEOD-CPLX GPT-CPLX ADENODEAMIN-MONOMER
  CPLX0-322 CPLX0-761)
 (PWY-CATALYZE SALVPURINE2-PWY XANTHOSINEPHOSPHORY-CPLX G7502-MONOMER
  CPLX0-322 GPT-CPLX HYPOXANPRIBOSYLTRAN-MONOMER DEOD-CPLX)
 (PWY-CATALYZE PWY-5686 CARBPSYN-CPLX ASPCARBTRANS-CPLX
  DIHYDROOROT-CPLX DIHYDROOROTOX-CPLX OROPRIBTRANS-CPLX
  OROTPDECARB-CPLX)
 (PWY-CATALYZE PWY-5687 UMPKI-CPLX CTPSYN-CPLX NUCLEOSIDE-DIP-KIN-CPLX)
 (PWY-CATALYZE PWY0-163 URACIL-PRIBOSYLTRANS-CPLX
  NUCLEOSIDE-DIP-KIN-CPLX CMPKI-MONOMER URPHOS-CPLX CYTIDEAM-CPLX
  CYTDEAM-MONOMER UDK-MONOMER)
 (PWY-CATALYZE PWY0-166 DCTP-DEAM-CPLX DUTP-PYROP-CPLX G7164-MONOMER
  THYMIDYLATESYN-CPLX DTMPKI-MONOMER NUCLEOSIDE-DIP-KIN-CPLX
  RIBONUCLEOSIDE-DIP-REDUCTI-CPLX RIBONUCLEOSIDE-DIP-REDUCTII-CPLX
  RIBONUCLEOSIDE-TRIP-REDUCT-CPLX)
 (PWY-CATALYZE PWY0-181 CYTIDEAM-CPLX DEOA-CPLX TDK-MONOMER)
 (PWY-CATALYZE ARO-PWY AROC-CPLX AROA-MONOMER AROL-MONOMER AROK-MONOMER
  AROE-MONOMER AROD-CPLX AROB-MONOMER AROG-CPLX AROH-CPLX AROF-CPLX
  CPLX0-7462)
 (PWY-CATALYZE PWY0-661 MONOMER0-702 PPENTOMUT-MONOMER EG10723-MONOMER)
 (PWY-CATALYZE PWY0-662 PRPPSYN-MONOMER)
 (PWY-CATALYZE BSUBPOLYAMSYN-PWY SPERMIDINESYN-CPLX SAMDECARB-CPLX)
 (PWY-CATALYZE PWY0-1303 SPERMIDINESYN-CPLX LYSDECARBOX-CPLX LDC2-CPLX)
 (PWY-CATALYZE PWY0-823 ARGDECARBOXBIO-CPLX ARGDECARBOXDEG-CPLX
  AGMATIN-CPLX)
 (PWY-CATALYZE BETSYN-PWY CHD-MONOMER BADH-CPLX)
 (PWY-CATALYZE PWY-40 ARGDECARBOXBIO-CPLX AGMATIN-CPLX)
 (PWY-CATALYZE PWY-46 ORNDECARBOX-BIO-CPLX)
 (PWY-CATALYZE ENTBACSYN-PWY ENTC-MONOMER ENTB-CPLX ENTA-CPLX
  ENTMULTI-CPLX)
 (PWY-CATALYZE PWY0-1280 ALD-CPLX LACTALDREDUCT-CPLX)
 (PWY-CATALYZE ETOH-ACETYLCOA-ANA-PWY ADHP-MONOMER ADHE-CPLX
  MHPF-MONOMER)
 (PWY-CATALYZE GLYCEROLMETAB-PWY GLYCDEH-CPLX)
 (PWY-CATALYZE PWY0-381 AERGLYC3PDEHYDROG-CPLX ANGLYC3PDEHYDROG-CPLX
  GLYCEROL-KIN-CPLX GLYCPDIESTER-PERI-CPLX GLYCPDIESTER-CYTO-MONOMER)
 (PWY-CATALYZE PWY-5386 GLYOXI-CPLX GLYOXII-MONOMER CPLX0-3954
  DLACTDEHYDROGFAD-MONOMER)
 (PWY-CATALYZE PWY-5453 G7558-MONOMER MONOMER0-149 MONOMER0-148
  G6967-MONOMER GLYCDEH-CPLX)
 (PWY-CATALYZE PWY-901 GLYOXIII-CPLX DLACTDEHYDROGFAD-MONOMER)
 (PWY-CATALYZE PWY0-1315 LACTALDREDUCT-CPLX)
 (PWY-CATALYZE PWY0-1317 ALD-CPLX L-LACTDEHYDROGFMN-MONOMER)
 (PWY-CATALYZE 2PHENDEG-PWY AMINEOXID-CPLX PHENDEHYD-CPLX)
 (PWY-CATALYZE GLUAMCAT-PWY GLUCOSAMINE-6-P-DEAMIN-CPLX
  NAG6PDEACET-CPLX)
 (PWY-CATALYZE 4AMINOBUTMETAB-PWY GABATRANSAM-CPLX G6646-MONOMER
  G6811-MONOMER SUCCSEMIALDDEHYDROG-MONOMER
  SUCCSEMIALDDEHYDROG-NAD-CPLX ALD-CPLX)
 (PWY-CATALYZE PWY-5698 CPLX-64 CPLX-7524)
 (PWY-CATALYZE CARNMET-PWY CROBETREDUCT-MONOMER CARNDEHYDRA-CPLX
  CARNRACE-MONOMER)
 (PWY-CATALYZE PUTDEG-PWY CPLX0-3641 G7596-MONOMER)
 (PWY-CATALYZE PWY0-1221 CPLX0-3943 ALDHDEHYDROG-MONOMER
  EG11822-MONOMER G6644-MONOMER)
 (PWY-CATALYZE PWY-5084 |E1(O)| |E2(O)| E3-CPLX)
 (PWY-CATALYZE ALADEG-PWY ALARACEBIOSYN-MONOMER CPLX0-7465
  DALADEHYDROG-CPLX)
 (PWY-CATALYZE AST-PWY ARGSUCCTRAN-MONOMER SUCCARGDIHYDRO-MONOMER
  SUCCORNTRANSAM-CPLX SUCCGLUALDDEHYD-MONOMER SUCCGLUDESUCC-MONOMER)
 (PWY-CATALYZE LCYSDEG-PWY CYSLYDE-MONOMER TRYPTOPHAN-CPLX
  CYSTATHIONINE-BETA-LYASE-CPLX)
 (PWY-CATALYZE GLUTAMINDEG-PWY GLUTAMINA-CPLX GLUTAMINB-CPLX
  G6810-MONOMER G6261-MONOMER)
 (PWY-CATALYZE GLYCLEAV-PWY E3-CPLX GCVP-CPLX GCVT-MONOMER)
 (PWY-CATALYZE PWY0-461 LYSDECARBOX-CPLX LDC2-CPLX)
 (PWY-CATALYZE PWY0-981 CPLX0-227) (PWY-CATALYZE PROUT-PWY PUTA-CPLX)
 (PWY-CATALYZE SERDEG-PWY LSERINEDEAM1-MONOMER LSERINEDEAM2-MONOMER
  CPLX0-7622 THREDEHYDCAT-CPLX)
 (PWY-CATALYZE PWY-5436 LTAA-CPLX ADHE-CPLX MHPF-MONOMER)
 (PWY-CATALYZE PWY-5437 THREDEHYDCAT-CPLX KETOBUTFORMLY-MONOMER
  PYRUVFORMLY-CPLX PHOSACETYLTRANS-CPLX PROPKIN-MONOMER
  ACETATEKINA-MONOMER)
 (PWY-CATALYZE THRDLCTCAT-PWY THREODEHYD-CPLX AMINEOXID-CPLX)
 (PWY-CATALYZE THREONINE-DEG2-PWY THREODEHYD-CPLX AKBLIG-CPLX)
 (PWY-CATALYZE TRYPDEG-PWY TRYPTOPHAN-CPLX)
 (PWY-CATALYZE HCAMHPDEG-PWY MHPCHYDROL-MONOMER MHPHYDROXY-MONOMER
  PHENPRODIOLDEHYDROG-MONOMER HCAMULTI-CPLX DHPDIOXYGEN-CPLX)
 (PWY-CATALYZE PWY0-321 G6719-MONOMER G6714-MONOMER G6716-MONOMER
  G6715-MONOMER G6708-MONOMER G6718-MONOMER CPLX0-1762)
 (PWY-CATALYZE PWY-1801 G6208-MONOMER CPLX0-3954 ADHC-CPLX)
 (PWY-CATALYZE PWY-5162 MHPDHYDROL-MONOMER MHPELY-MONOMER ADHE-CPLX
  MHPF-MONOMER)
 (PWY-CATALYZE PWY0-1309 EG10144-MONOMER G6576-MONOMER)
 (PWY-CATALYZE FUCCAT-PWY CPLX0-7633 FUCULOKIN-MONOMER CPLX0-7631)
 (PWY-CATALYZE GLUCOSE1PMETAB-PWY GLUCDEHYDROG-MONOMER G6437-MONOMER
  EG11470-MONOMER EG11195-MONOMER G6425-MONOMER GLUCOSE-1-PHOSPHAT-CPLX
  EG11850-MONOMER PHOSPHOGLUCMUT-MONOMER GLUCOKIN-MONOMER)
 (PWY-CATALYZE LYXMET-PWY CPLX0-7652 LYXK-CPLX EG12286-MONOMER
  RIBULPEPIM-CPLX EG12287-MONOMER)
 (PWY-CATALYZE MANNCAT-PWY MANNPISOM-MONOMER MANNKIN-MONOMER)
 (PWY-CATALYZE PWY0-1300 EG13236-MONOMER GKI-MONOMER)
 (PWY-CATALYZE PWY0-1301 ALPHAGALACTOSID-CPLX)
 (PWY-CATALYZE PWY0-1314 1-PFK)
 (PWY-CATALYZE PWY0-44 RIB5PISOMB-CPLX EG11957-MONOMER EG11956-MONOMER)
 (PWY-CATALYZE RHAMCAT-PWY RHAMNULPALDOL-CPLX RHAMNULOKIN-MONOMER
  CPLX0-7652)
 (PWY-CATALYZE RIBOKIN-PWY CPLX0-7647 CPLX0-7646)
 (PWY-CATALYZE DARABCATK12-PWY CPLX0-7631 FUCULOKIN-MONOMER CPLX0-7633
  ALD-CPLX)
 (PWY-CATALYZE ARABCAT-PWY ARABISOM-CPLX RIBULPEPIM-CPLX
  RIBULOKIN-CPLX)
 (PWY-CATALYZE BGALACT-PWY BETAGALACTOSID-CPLX)
 (PWY-CATALYZE PWY0-1182 TREHALAPERI-MONOMER TREHALACYTO-MONOMER
  GLUCOKIN-MONOMER)
 (PWY-CATALYZE TREDEGLOW-PWY TRE6PHYDRO-MONOMER GLUCOKIN-MONOMER)
 (PWY-CATALYZE XYLCAT-PWY CPLX0-7466 XYLISOM-CPLX)
 (PWY-CATALYZE GLYCOLATEMET-PWY GLY3KIN-MONOMER GLYOCARBOLIG-CPLX
  CPLX0-7458 G6278-MONOMER CPLX0-7616)
 (PWY-CATALYZE GLYOXDEG-PWY MALSYNG-MONOMER CPLX0-7458)
 (PWY-CATALYZE PWY0-1313 ACS-MONOMER)
 (PWY-CATALYZE PWY0-301 G7859-MONOMER EG12286-MONOMER G7858-MONOMER
  G7860-MONOMER G7855-MONOMER)
 (PWY-CATALYZE PYRUVDEHYD-PWY E1P-CPLX E2P-MONOMER E3-CPLX)
 (PWY-CATALYZE PWY0-1312 ACETATEKINB-MONOMER PHOSACETYLTRANS-CPLX)
 (PWY-CATALYZE PROPIONMET-PWY METHYLMALONYL-COA-EPIM-MONOMER
  METHYLMALONYL-COA-MUT-MONOMER PROPIONYL-COA-CARBOXY-MONOMER)
 (PWY-CATALYZE PWY0-42 ACS-MONOMER CPLX0-251 G6199-MONOMER
  ACONITATEDEHYDRB-MONOMER CPLX0-1021)
 (PWY-CATALYZE PWY0-43 METHYLMALONYL-COA-MUT-MONOMER CPLX0-254
  G7517-MONOMER)
 (PWY-CATALYZE ACETOACETATE-DEG-PWY ACETYL-COA-ACETYLTRANSFER-CPLX
  ACETOACETYL-COA-TRANSFER-CPLX)
 (PWY-CATALYZE FAO-PWY FAO-CPLX CPLX0-1668 ACYLCOASYN-CPLX CPLX0-1669
  ACYLCOADEHYDROG-MONOMER G6918-MONOMER EG11811-MONOMER FADB-CPLX
  G6708-MONOMER CPLX0-1666)
 (PWY-CATALYZE CYANCAT-PWY CARBODEHYDRAT-CPLX CPLX0-7520)
 (PWY-CATALYZE ALKANEMONOX-PWY CPLX0-224 CPLX0-225)
 (PWY-CATALYZE SO4ASSIM-PWY PAPSSULFOTRANS-CPLX SULFITE-REDUCT-CPLX
  ADENYLYLSULFKIN-CPLX CPLX0-7428)
 (PWY-CATALYZE PWY0-1295 CYTIDEAM-CPLX URPHOS-CPLX PPENTOMUT-MONOMER)
 (PWY-CATALYZE PWY0-1296 XANTHOSINEPHOSPHORY-CPLX ADENODEAMIN-MONOMER
  PPENTOMUT-MONOMER DEOD-CPLX)
 (PWY-CATALYZE PWY0-1297 DEOD-CPLX ADENODEAMIN-MONOMER
  PPENTOMUT-MONOMER DEOXYRIBOSE-P-ALD-MONOMER ADHE-CPLX MHPF-MONOMER)
 (PWY-CATALYZE PWY0-1298 CYTIDEAM-CPLX DEOA-CPLX PPENTOMUT-MONOMER
  DEOXYRIBOSE-P-ALD-MONOMER ADHE-CPLX MHPF-MONOMER)
 (PWY-CATALYZE DETOX1-PWY SUPEROX-DISMUTMN-CPLX SUPEROX-DISMUTFE-CPLX
  G6886-MONOMER HYDROPEROXIDII-CPLX HYDROPEROXIDI-CPLX)
 (PWY-CATALYZE PWY0-1261 G7263-MONOMER G6880-MONOMER)
 (PWY-CATALYZE PWY0-521 CPLX0-821 G7726-MONOMER CPLX0-3861)
 (PWY-CATALYZE GALACTARDEG-PWY CPLX0-7615 TSA-REDUCT-MONOMER
  G6278-MONOMER GALACTARDEHYDRA-MONOMER GKI-MONOMER)
 (PWY-CATALYZE GALACTCAT-PWY DEHYDDEOXGALACTKIN-MONOMER
  DEHYDDEOXPHOSGALACT-ALDOL-MONOMER GALACTONATE-DEHYDRATASE-MONOMER)
 (PWY-CATALYZE GALACTUROCAT-PWY ALTRODEHYDRAT-MONOMER
  DEOXYGLUCONOKIN-MONOMER ALTRO-OXIDOREDUCT-MONOMER UXAC-MONOMER)
 (PWY-CATALYZE GLUCARDEG-PWY CPLX0-7615 TSA-REDUCT-MONOMER
  G6278-MONOMER GLUCARDEHYDRA-MONOMER GKI-MONOMER)
 (PWY-CATALYZE GLUCUROCAT-PWY MANNONDEHYDRAT-MONOMER
  DEOXYGLUCONOKIN-MONOMER MANNONOXIDOREDUCT-MONOMER UXAC-MONOMER
  BETA-GLUCURONID-MONOMER)
 (PWY-CATALYZE IDNCAT-PWY GLUCONREDUCT-MONOMER GLUCONOKINI-MONOMER
  IDONDEHYD-MONOMER)
 (PWY-CATALYZE PWY0-1306 G7945-MONOMER ALTRO-OXIDOREDUCT-MONOMER
  ALTRODEHYDRAT-MONOMER DEOXYGLUCONOKIN-MONOMER)
 (PWY-CATALYZE GALACTITOLCAT-PWY 6PFK-2-CPX CPLX0-240 CPLX0-241
  GALACTITOLPDEHYD-MONOMER)
 (PWY-CATALYZE MANNIDEG-PWY MANNPDEHYDROG-MONOMER)
 (PWY-CATALYZE SORBDEG-PWY SORB6PDEHYDROG-CPLX)
 (PWY-CATALYZE PWY0-1299 ARGDECARBOXDEG-CPLX)
 (PWY-CATALYZE PWY0-1305 GLUTDECARBOXA-CPLX GLUTDECARBOXB-CPLX)
 (PWY-CATALYZE ENTNER-DOUDOROFF-PWY KDPGALDOL-4OH2OXOGLUTARALDOL-CPLX
  PGLUCONDEHYDRAT-MONOMER)
 (PWY-CATALYZE FERMENTATION-PWY PHOSACETYLTRANS-CPLX
  ACETATEKINB-MONOMER ACETATEKINA-MONOMER KETOBUTFORMLY-MONOMER
  PYRUVFORMLY-CPLX ADHE-CPLX ADHP-MONOMER PKII-CPLX PKI-COMPLEX
  DLACTDEHYDROGNAD-MONOMER FUMARASE-C FUMARASE-B FUMARASE-A
  MALATE-DEHASE PEPCARBOX-CPLX FHLMULTI-CPLX PYRUVOXID-CPLX
  FUMARATE-REDUCTASE)
 (PWY-CATALYZE GLYCOLYSIS PKII-CPLX PKI-COMPLEX ENOLASE-CPLX
  PHOSGLYCMUTASE PGAM2-MONOMER PGMI-MONOMER PGK GAPDH-A-CPLX TPI
  FRUCBISALD-CLASSII FRUCBISALD-CLASSI 6PFK-2-CPX 6PFK-1-CPX PGLUCISOM
  PEPSYNTH-CPLX F16B-CPLX CPLX0-303 EG11239-MONOMER)
 (PWY-CATALYZE NONOXIPENT-PWY TRANSALDOLB-CPLX TRANSALDOLA-MONOMER
  TRANSKETOI-CPLX CPLX0-1261 RIBULP3EPIM-MONOMER RIB5PISOMB-CPLX
  RIB5PISOMA-CPLX)
 (PWY-CATALYZE OXIDATIVEPENT-PWY 6PGLUCONOLACT-MONOMER
  6PGLUCONDEHYDROG-CPLX GLU6PDEHYDROG-MONOMER)
 (PWY-CATALYZE AERESPDON-PWY AERGLYC3PDEHYDROG-CPLX SUCC-DEHASE
  DLACTDEHYDROGFAD-MONOMER L-LACTDEHYDROGFMN-MONOMER NADH-DHI-CPLX
  NADH-DHII-MONOMER)
 (PWY-CATALYZE ANA-ELECT-TRANS-PWY)
 (PWY-CATALYZE ANARESP1-PWY PKII-CPLX PKI-COMPLEX PYRUVATEDEH-CPLX
  |CITRATE-(SI)-SYNTHASE| ACONITASE-MONOMER ACONITATEDEHYDRB-MONOMER
  ISOCITHASE-CPLX PEPCARBOX-CPLX MALATE-DEHASE FUMARASE-C FUMARASE-B
  FUMARASE-A KETOBUTFORMLY-MONOMER PYRUVFORMLY-CPLX ENOLASE-CPLX
  FHLMULTI-CPLX FUMARATE-REDUCTASE)
 (PWY-CATALYZE ANARESPACC-PWY DIMESULFREDUCT-CPLX CPLX0-1601
  TMAOREDUCTII-MONOMER THTOREDUCT-MONOMER NAP-CPLX CPLX-63
  TMAOREDUCTI-CPLX FUMARATE-REDUCTASE NRFMULTI-CPLX
  CYTOCHROMEC552-MONOMER)
 (PWY-CATALYZE ANARESPDON-PWY ANGLYC3PDEHYDROG-CPLX
  L-LACTDEHYDROGFMN-MONOMER FORMATEDEHYDROGO-CPLX FORMATEDEHYDROGN-CPLX
  NADH-DHI-CPLX FORMHYDROGI-CPLX FORMHYDROG2-CPLX)
 (PWY-CATALYZE GLYOXYLATE-BYPASS MALATE-DEHASE MALATE-SYNTHASE
  ISOCIT-LYASE |CITRATE-(SI)-SYNTHASE| ACONITASE-MONOMER
  ACONITATEDEHYDRB-MONOMER)
 (PWY-CATALYZE TCA MALATE-DEHASE FUMARASE-C FUMARASE-B FUMARASE-A
  SUCCCOASYN 2OXOGLUTARATEDEH-CPLX ISOCITHASE-CPLX
  |CITRATE-(SI)-SYNTHASE| ACONITASE-MONOMER ACONITATEDEHYDRB-MONOMER
  SUCC-DEHASE EG12069-MONOMER))

((ENZYME N-ACETYLTRANSFER-CPLX EG10063)
 (ENZYME ACETYLGLUTKIN-CPLX EG10064)
 (ENZYME N-ACETYLGLUTPREDUCT-MONOMER EG10065)
 (ENZYME ACETYLORNDEACET-CPLX EG11286) (ENZYME EG10943-MONOMER EG10943)
 (ENZYME CPLX0-1141 EG10941) (ENZYME MONOMER0-1241 G0-9281)
 (ENZYME VALINE-PYRUVATE-AMINOTRANSFER-MONOMER EG10107)
 (ENZYME CPLX0-248 G7325) (ENZYME ASNSYNA-CPLX EG10091)
 (ENZYME ASNSYNB-CPLX EG10092) (ENZYME ASPARTASE-CPLX EG10095)
 (ENZYME CPLX0-2901 EG11747) (ENZYME CPLX0-237 EG10187)
 (ENZYME ACSERLYA-CPLX EG10192) (ENZYME GLUTAMINESYN-OLIGOMER EG10383)
 (ENZYME HISTDEHYD-CPLX EG10447) (ENZYME HISTPHOSTRANS-CPLX EG10446)
 (ENZYME IMIDHISTID-CPLX EG10445)
 (ENZYME GLUTAMIDOTRANS-CPLX EG10448 EG10450)
 (ENZYME PRIBFAICARPISOM-MONOMER EG10444)
 (ENZYME HISTCYCLOPRATPPHOS EG10451) (ENZYME CPLX0-7614 EG10449)
 (ENZYME THREDEHYDSYN-CPLX EG10493)
 (ENZYME 3-ISOPROPYLMALDEHYDROG-CPLX EG11577)
 (ENZYME 2-ISOPROPYLMALATESYN-MONOMER EG11226)
 (ENZYME 3-ISOPROPYLMALISOM-CPLX EG11575 EG11576)
 (ENZYME DIAMINOPIMEPIM-MONOMER EG10209)
 (ENZYME DIAMINOPIMDECARB-CPLX EG10549) (ENZYME CPLX0-3161 EG10208)
 (ENZYME ACETYLORNTRANSAM-CPLX EG10066) (ENZYME CPLX0-3181 EG10207)
 (ENZYME DIHYDROPICRED-CPLX EG10206)
 (ENZYME DIHYDRODIPICSYN-CPLX EG10205) (ENZYME HOMSUCTRAN-CPLX EG10581)
 (ENZYME HOMOCYSMET-MONOMER EG10584) (ENZYME EG10564-MONOMER EG10564)
 (ENZYME O-SUCCHOMOSERLYASE-CPLX EG10582)
 (ENZYME ASPKINIII-CPLX EG10550)
 (ENZYME ASP-SEMIALDEHYDE-DEHYDROGENASE-CPLX EG10088)
 (ENZYME ASPKINIHOMOSERDEHYDROGI-CPLX EG10998)
 (ENZYME ASPKINIIHOMOSERDEHYDROGII-CPLX EG10590)
 (ENZYME ASPAMINOTRANS-DIMER EG10096)
 (ENZYME PYRROLINECARBREDUCT-CPLX EG10769)
 (ENZYME GLUTSEMIALDEHYDROG-CPLX EG10767) (ENZYME GLUTKIN-CPLX EG10768)
 (ENZYME GDHA-CPLX EG10372) (ENZYME GLUTAMATESYN-CPLX EG10404 EG10403)
 (ENZYME PGLYCDEHYDROG-CPLX EG10944)
 (ENZYME PSERPHOSPHA-MONOMER EG10945) (ENZYME HOMOSERKIN-CPLX EG10999)
 (ENZYME THRESYN-MONOMER EG11000) (ENZYME PRAI-IGPS EG11026)
 (ENZYME ANTHRANSYNCOMPII EG11027)
 (ENZYME ANTHRANSYN-CPLX EG11027 EG11028)
 (ENZYME TRYPSYN-APROTEIN EG11024) (ENZYME CPLX0-2401 EG11025)
 (ENZYME TYRB-DIMER EG11040)
 (ENZYME CHORISMUTPREPHENDEHYDRAT-CPLX EG10707)
 (ENZYME CHORISMUTPREPHENDEHYDROG-CPLX EG11039)
 (ENZYME DIHYDROXYACIDDEHYDRAT-CPLX EG10496)
 (ENZYME CPLX0-7643 EG10495)
 (ENZYME ACETOLACTSYNI-CPLX EG10502 EG10494)
 (ENZYME ACETOLACTSYNII-CPLX EG10501 EG10498 G8221)
 (ENZYME ACETOLACTSYNIII-CPLX EG10499 EG10500)
 (ENZYME ARGS-MONOMER EG10071) (ENZYME CYSS-MONOMER EG10196)
 (ENZYME GLNS-MONOMER EG10390) (ENZYME ILES-MONOMER EG10492)
 (ENZYME LEUS-MONOMER EG10532) (ENZYME VALS-MONOMER EG11067)
 (ENZYME ALAS-CPLX EG10034) (ENZYME ASNS-CPLX EG10094)
 (ENZYME ASPS-CPLX EG10097) (ENZYME TYRS-CPLX EG11043)
 (ENZYME TRPS-CPLX EG11030) (ENZYME THRS-CPLX EG11001)
 (ENZYME SERS-CPLX EG10947) (ENZYME PROS-CPLX EG10770)
 (ENZYME PHES-CPLX EG10710 EG10709) (ENZYME METG-CPLX EG10586)
 (ENZYME LYSU-CPLX EG10553) (ENZYME LYSS-CPLX EG10552)
 (ENZYME HISS-CPLX EG10453) (ENZYME GLYS-CPLX EG10409 EG10410)
 (ENZYME PEPCARBOXYKIN-MONOMER EG10688) (ENZYME MALIC-NAD-CPLX EG10948)
 (ENZYME MALIC-NADP-CPLX G7293) (ENZYME AMYLOMALT-MONOMER EG10561)
 (ENZYME GLYCOPHOSPHORYL-CPLX EG10380) (ENZYME EG10381-MONOMER EG10381)
 (ENZYME MALDEXPHOSPHORYL-CPLX EG10560)
 (ENZYME MALTODEXGLUCOSID-MONOMER EG10565)
 (ENZYME CPM-KDOSYNTH-MONOMER EG10519)
 (ENZYME KDO-8PPHOSPHAT-CPLX G7663) (ENZYME KDO-8PSYNTH-CPLX EG10518)
 (ENZYME CPLX0-1262 G7662) (ENZYME CPLX0-3929 EG10973)
 (ENZYME CPLX0-3661 G7590) (ENZYME EG11736-MONOMER EG11736)
 (ENZYME CPLX0-3681 EG10838) (ENZYME CPLX0-7660 G6106)
 (ENZYME DTDPDEHYDRHAMEPIM-MONOMER EG11979)
 (ENZYME DTDPDEHYRHAMREDUCT-MONOMER EG12411)
 (ENZYME DTDPGLUCDEHYDRAT-CPLX EG12412)
 (ENZYME DTDPGLUCOSEPP-MONOMER EG11978)
 (ENZYME TREHALOSE6PSYN-MONOMER EG11751)
 (ENZYME TREHALOSEPHOSPHASYN-MONOMER EG11752)
 (ENZYME GLYCOGENSYN-CPLX EG10377)
 (ENZYME GLYCOGEN-BRANCH-MONOMER EG10378)
 (ENZYME GLUC1PADENYLTRANS-CPLX EG10379)
 (ENZYME GDPMANDEHYDRA-CPLX EG11787)
 (ENZYME GALACTOKIN-MONOMER EG10363)
 (ENZYME GALACTURIDYLYLTRANS-CPLX EG10366)
 (ENZYME UDPGLUCEPIM-CPLX EG10362)
 (ENZYME GLUC1PURIDYLTRANS-CPLX EG11319 G7093)
 (ENZYME UGD-MONOMER G7091) (ENZYME CPLX0-3881 EG11788)
 (ENZYME GLCNACPTRANS-MONOMER EG10840)
 (ENZYME UDPMANACATRANS-MONOMER EG11458)
 (ENZYME UDPMANNACADEHYDROG-MONOMER EG11452)
 (ENZYME G7800-MONOMER G7800) (ENZYME TDPFUCACTRANS-MONOMER EG11455)
 (ENZYME UDPGLCNACEPIM-MONOMER EG11451)
 (ENZYME RFFTRANS-MONOMER EG11456)
 (ENZYME DTDPGLUCOSEPP2-MONOMER EG11454)
 (ENZYME DTDPGLUCDEHYDRAT2-MONOMER EG11453)
 (ENZYME KDOTRANS-MONOMER EG10520)
 (ENZYME GDPMANMANHYDRO-MONOMER EG11789)
 (ENZYME MANNPGUANYLTRANGDP-MONOMER EG10161)
 (ENZYME PHOSMANMUT-MONOMER EG10162) (ENZYME CPLX0-7415 EG10546)
 (ENZYME TETRAACYLDISACC4KIN-MONOMER EG11409)
 (ENZYME EG12666-MONOMER EG12666)
 (ENZYME UDPHYDROXYMYRGLUCOSAMNACETYLTRANS-MONO EG10316)
 (ENZYME UDPACYLGLCNACDEACETYL-MONOMER EG10265)
 (ENZYME UDPNACETYLGLUCOSAMACYLTRANS-CPLX EG10545)
 (ENZYME NAG1P-URIDYLTRANS-CPLX EG11198)
 (ENZYME L-GLN-FRUCT-6-P-AMINOTRANS-CPLX EG10382)
 (ENZYME PHOSGLUCOSAMINEMUT-MONOMER EG11553)
 (ENZYME UDPNACETYLGLUCOSAMENOLPYRTRANS-MONOMER EG11358)
 (ENZYME UDPNACETYLMURAMATEDEHYDROG-MONOMER EG11205)
 (ENZYME NACGLCTRANS-MONOMER EG10623)
 (ENZYME UDP-NACMURALGLDAPAALIG-MONOMER EG10622)
 (ENZYME UDP-NACMUR-ALA-LIG-MONOMER EG10619)
 (ENZYME UDP-NACMURALA-GLU-LIG-MONOMER EG10620)
 (ENZYME GLUTRACE-CPLX EG11204)
 (ENZYME UDP-NACMURALGLDAPLIG-MONOMER EG10621)
 (ENZYME DALADALALIGA-MONOMER EG10213)
 (ENZYME DALADALALIGB-CPLX EG10214)
 (ENZYME PHOSNACMURPENTATRANS-MONOMER EG10604)
 (ENZYME DXPREDISOM-CPLX EG12715) (ENZYME EG10370-MONOMER EG10370)
 (ENZYME CPLX0-7564 EG11081) (ENZYME CPLX0-234 G7423)
 (ENZYME CPLX0-3841 EG11294) (ENZYME CPLX0-721 EG11816)
 (ENZYME FPPSYN-MONOMER EG10508) (ENZYME IPPISOM-MONOMER G7508)
 (ENZYME S-ADENMETSYN-CPLX EG10589) (ENZYME ADOMETSYN2-CPLX)
 (ENZYME COADTRI-CPLX EG11190) (ENZYME EG12312-MONOMER EG12312)
 (ENZYME CPLX0-341 EG10004) (ENZYME PANTOTHENATE-KIN-CPLX EG10922)
 (ENZYME G6340-MONOMER G6340) (ENZYME G6339-MONOMER G6339)
 (ENZYME CPLX0-782 EG11306) (ENZYME EG11591-MONOMER EG11591)
 (ENZYME AAS-MONOMER EG11679) (ENZYME EG11796-MONOMER EG11796)
 (ENZYME PYRNUTRANSHYDROGEN-CPLX EG10744 EG10745)
 (ENZYME CPLX0-682 EG12192) (ENZYME 6PFK-1-MONOMER EG10699)
 (ENZYME NADPPHOSPHAT-MONOMER) (ENZYME NMNAMIDOHYDRO-MONOMER)
 (ENZYME EG11702-MONOMER EG11702)
 (ENZYME NICOTINATEPRIBOSYLTRANS-MONOMER EG10742)
 (ENZYME NICOTINAMID-MONOMER EG11135) (ENZYME NADNUCLEOSID-MONOMER)
 (ENZYME NMNNUCLEOSID-MONOMER)
 (ENZYME NICONUCADENYLYLTRAN-MONOMER G6350)
 (ENZYME NAD-SYNTH-CPLX EG10663) (ENZYME QUINOPRIBOTRANS-CPLX EG11546)
 (ENZYME QUINOLINATE-SYNTHA-MONOMER EG10630)
 (ENZYME L-ASPARTATE-OXID-MONOMER EG10631) (ENZYME CPLX0-7426 EG10017)
 (ENZYME UPPSYN-CPLX G6092) (ENZYME SIROHEMESYN-CPLX EG10188)
 (ENZYME PROTOPORGENOXI-MONOMER EG11485)
 (ENZYME PROTOHEME-FERROCHELAT-MONOMER EG10431)
 (ENZYME UROGENDECARBOX-MONOMER EG11543) (ENZYME HEMN-MONOMER EG11836)
 (ENZYME COPROGENOXI-MONOMER EG12189) (ENZYME DMK-MONOMER EG11880)
 (ENZYME NAPHTHOATE-SYN-MONOMER EG11368) (ENZYME MENE-CPLX EG12437)
 (ENZYME O-SUCCINYLBENZOATE-COA-SYN-MONOMER EG11532)
 (ENZYME MENF-CPLX EG12362) (ENZYME CPLX0-7525 EG10579)
 (ENZYME OCTAPRENYL-METHYL-METHOXY-BENZOQ-OH-MON G6365)
 (ENZYME 2-OCTAPRENYL-METHOXY-BENZOQ-METH-MONOMER EG11473)
 (ENZYME OCTAPRENYL-METHOXYPHENOL-OH-MONOMER EG11324)
 (ENZYME DHHB-METHYLTRANSFER-CPLX EG11143)
 (ENZYME 2-OCTAPRENYLPHENOL-HYDROX-MONOMER EG11476)
 (ENZYME CPLX0-301 EG11396) (ENZYME UBIX-MONOMER EG11044)
 (ENZYME 4OHBENZOATE-OCTAPRENYLTRANSFER-MONOMER EG11370)
 (ENZYME CHORPYRLY-MONOMER EG11369) (ENZYME PRODISULFREDUCT-MONOMER)
 (ENZYME GLUTATHIONE-REDUCT-NADPH-CPLX EG10412)
 (ENZYME GLUTCYSLIG-MONOMER EG10418)
 (ENZYME GLUTATHIONE-SYN-CPLX EG10419)
 (ENZYME THIOREDOXIN-REDUCT-NADPH-CPLX EG11032)
 (ENZYME UROGENIIISYN-MONOMER EG10430)
 (ENZYME OHMETHYLBILANESYN-MONOMER EG10429)
 (ENZYME PORPHOBILSYNTH-CPLX EG10428)
 (ENZYME GSAAMINOTRANS-CPLX EG10432) (ENZYME CPLX0-3741 EG10427)
 (ENZYME GLURS-MONOMER EG10407) (ENZYME RIBF-MONOMER EG11079)
 (ENZYME CPLX0-3952 EG11406) (ENZYME LUMAZINESYN-CPLX EG11322)
 (ENZYME RIBOPHOSPHAT-MONOMER) (ENZYME DIOHBUTANONEPSYN-CPLX EG10465)
 (ENZYME CPLX0-7659 EG11321) (ENZYME GTP-CYCLOHYDRO-II-CPLX EG11331)
 (ENZYME DETHIOBIOTIN-SYN-CPLX EG10120)
 (ENZYME BIOTIN-SYN-CPLX EG10118) (ENZYME DAPASYN-CPLX EG10117)
 (ENZYME 7KAPSYN-CPLX EG10121) (ENZYME COBS-MONOMER EG12150)
 (ENZYME RIBAZOLEPHOSPHAT-MONOMER G6349) (ENZYME COBU-CPLX EG13238)
 (ENZYME DMBPPRIBOSYLTRANS-CPLX EG12151)
 (ENZYME COBALADENOSYLTRANS-MONOMER EG10130)
 (ENZYME FORMYLTHFDEFORMYL-CPLX EG11819)
 (ENZYME GCVMULTI-CPLX EG11442 EG10371 EG11810 EG10543)
 (ENZYME METHYLENETHFREDUCT-CPLX EG10585)
 (ENZYME HOMOCYSMETB12-MONOMER EG10587) (ENZYME ADCLY-CPLX EG11493)
 (ENZYME H2PTEROATESYNTH-CPLX EG50011)
 (ENZYME PABASYN-CPLX EG10682 EG10683) (ENZYME FOLD-CPLX EG10328)
 (ENZYME DIHYDROFOLATEREDUCT-MONOMER EG10326)
 (ENZYME G6862-MONOMER G6862)
 (ENZYME H2PTERIDINEPYROPHOSPHOKIN-MONOMER EG11374)
 (ENZYME CPLX0-3936 EG11673)
 (ENZYME DIHYDRONEOPTERIN-MONO-P-DEPHOS-MONOMER)
 (ENZYME H2NEOPTERINP3PYROPHOSPHOHYDRO-MONOMER EG11138)
 (ENZYME FOLE-CPLX EG11375) (ENZYME FORMATETHFLIG-MONOMER)
 (ENZYME GLYOHMETRANS-CPLX EG10408) (ENZYME FOLC-MONOMER EG10327)
 (ENZYME MONOMER0-1661) (ENZYME PANTOATE-BETA-ALANINE-LIG-CPLX EG11746)
 (ENZYME 2-DEHYDROPANTOATE-REDUCT-MONOMER G6239)
 (ENZYME 3-METHYL-2-OXOBUT-OHCH3XFER-CPLX EG11675)
 (ENZYME BRANCHED-CHAINAMINOTRANSFER-CPLX EG10497)
 (ENZYME PDXK-CPLX G7259) (ENZYME PDXY-MONOMER G6879)
 (ENZYME PDXH-CPLX EG11487) (ENZYME ERYTH4PDEHYDROG-CPLX EG10368)
 (ENZYME CPLX0-743 G6237) (ENZYME CPLX0-321 EG10693)
 (ENZYME ERYTHRON4PDEHYDROG-MONOMER G0-9461)
 (ENZYME PSERTRANSAM-CPLX EG10946) (ENZYME PDXA-MONOMER EG10691)
 (ENZYME LAUROYLACYLTRAN-MONOMER EG10464)
 (ENZYME MYRISTOYLACYLTRAN-MONOMER EG10614)
 (ENZYME EG11189-MONOMER EG11189) (ENZYME EG12210-MONOMER EG12210)
 (ENZYME EG11339-MONOMER EG11339) (ENZYME EG11340-MONOMER EG11340)
 (ENZYME EG11341-MONOMER EG11341) (ENZYME EG11425-MONOMER EG11425)
 (ENZYME EG11351-MONOMER EG11351) (ENZYME EG11352-MONOMER EG11352)
 (ENZYME EG11353-MONOMER EG11353) (ENZYME EG11423-MONOMER EG11423)
 (ENZYME BIOTINLIG-MONOMER EG10123)
 (ENZYME BIOTIN-CARBOXYL-CPLX EG10276)
 (ENZYME ACETYL-COA-CARBOXYLTRANSFER-CPLX EG10217 EG11647)
 (ENZYME 3-OXOACYL-ACP-SYNTHII-CPLX EG12606)
 (ENZYME MALONYL-COA-ACP-TRANSACYL-MONOMER EG11317)
 (ENZYME CPLX0-252 EG10277)
 (ENZYME ACETYL-COA-CARBOXYLMULTI-CPLX EG10275 EG10276 EG11647 EG10217)
 (ENZYME ENOYL-ACP-REDUCT-NADH-MONOMER EG11528)
 (ENZYME 3-OXOACYL-ACP-REDUCT-MONOMER EG11318)
 (ENZYME FABB-CPLX EG10274) (ENZYME FABZ-CPLX EG11284)
 (ENZYME FABA-CPLX EG10273) (ENZYME CFA-CPLX EG11531)
 (ENZYME PHOSPHASERSYN-CPLX EG10781)
 (ENZYME PHOSPHASERDECARB-CPLX EG10775)
 (ENZYME CDPDIGLYSYN-MONOMER EG10139)
 (ENZYME GLYC3PDEHYDROGBIOSYN-CPLX EG20091)
 (ENZYME GLYCEROL-3-P-ACYLTRANSFER-MONOMER EG10740)
 (ENZYME 1-ACYLGLYCEROL-3-P-ACYLTRANSFER-MONOMER EG11377)
 (ENZYME PGPPHOSPHAA-MONOMER EG10704)
 (ENZYME PGPPHOSPHAB-MONOMER EG10705) (ENZYME PGPPHOSPHAC-MONOMER)
 (ENZYME CARDIOLIPSYN-MONOMER EG11608) (ENZYME G6406-MONOMER G6406)
 (ENZYME PHOSPHAGLYPSYN-MONOMER EG10706)
 (ENZYME PPPGPPHYDRO-CPLX EG10413) (ENZYME SPOT-MONOMER EG10966)
 (ENZYME RELA-MONOMER EG10835) (ENZYME PRPPAMIDOTRANS-CPLX EG10794)
 (ENZYME GLYCRIBONUCSYN-MONOMER EG10792) (ENZYME GART-MONOMER EG10799)
 (ENZYME GARTRANSFORMYL2-MONOMER EG11809)
 (ENZYME FGAMSYN-MONOMER EG10797) (ENZYME AIRS-CPLX EG10798)
 (ENZYME SAICARSYN-CPLX EG10791)
 (ENZYME AICARTRANSIMPCYCLO-CPLX EG10795)
 (ENZYME ADENYLOSUCCINATE-SYN-DIMER EG10790)
 (ENZYME ASL-MONOMER EG11314) (ENZYME ADENYL-KIN-MONOMER EG10032)
 (ENZYME IMP-DEHYDROG-CPLX EG10421) (ENZYME GMP-SYN-CPLX EG10420)
 (ENZYME GUANYL-KIN-CPLX EG10965) (ENZYME PURE-CPLX EG10793)
 (ENZYME PURK-CPLX EG10796) (ENZYME AMP-NUCLEOSID-CPLX EG10039)
 (ENZYME ADENPRIBOSYLTRAN-CPLX EG10051)
 (ENZYME CPLX0-761 G7487 G7486 G7485) (ENZYME G7502-MONOMER G7502)
 (ENZYME CPLX0-322 EG11102) (ENZYME GPT-CPLX EG10414)
 (ENZYME HYPOXANPRIBOSYLTRAN-MONOMER EG20098)
 (ENZYME CARBPSYN-CPLX EG10134 EG10135)
 (ENZYME ASPCARBTRANS-CPLX EG10811 EG10805)
 (ENZYME DIHYDROOROT-CPLX EG10806) (ENZYME DIHYDROOROTOX-CPLX EG10807)
 (ENZYME OROPRIBTRANS-CPLX EG10808) (ENZYME OROTPDECARB-CPLX EG10809)
 (ENZYME UMPKI-CPLX EG11539) (ENZYME CTPSYN-CPLX EG10810)
 (ENZYME URACIL-PRIBOSYLTRANS-CPLX EG11332)
 (ENZYME CMPKI-MONOMER EG11265) (ENZYME CYTDEAM-MONOMER EG11326)
 (ENZYME UDK-MONOMER EG11701) (ENZYME DCTP-DEAM-CPLX EG11418)
 (ENZYME DUTP-PYROP-CPLX EG10251) (ENZYME G7164-MONOMER G7164)
 (ENZYME THYMIDYLATESYN-CPLX EG11002) (ENZYME DTMPKI-MONOMER EG12302)
 (ENZYME NUCLEOSIDE-DIP-KIN-CPLX EG10650)
 (ENZYME RIBONUCLEOSIDE-DIP-REDUCTI-CPLX EG10661 EG10660)
 (ENZYME RIBONUCLEOSIDE-DIP-REDUCTII-CPLX EG12381 EG20257)
 (ENZYME RIBONUCLEOSIDE-TRIP-REDUCT-CPLX EG11417)
 (ENZYME TDK-MONOMER EG10994) (ENZYME AROC-CPLX EG10075)
 (ENZYME AROA-MONOMER EG10073) (ENZYME AROL-MONOMER EG10082)
 (ENZYME AROK-MONOMER EG10081) (ENZYME AROE-MONOMER EG10077)
 (ENZYME AROD-CPLX EG10076) (ENZYME AROB-MONOMER EG10074)
 (ENZYME AROG-CPLX EG10079) (ENZYME AROH-CPLX EG10080)
 (ENZYME AROF-CPLX EG10078) (ENZYME CPLX0-7462 EG11234)
 (ENZYME MONOMER0-702) (ENZYME EG10723-MONOMER EG10723)
 (ENZYME PRPPSYN-MONOMER EG10774) (ENZYME SAMDECARB-CPLX EG10962)
 (ENZYME SPERMIDINESYN-CPLX EG10963) (ENZYME CHD-MONOMER EG10109)
 (ENZYME BADH-CPLX EG10110) (ENZYME ARGDECARBOXBIO-CPLX EG10959)
 (ENZYME AGMATIN-CPLX EG10960) (ENZYME ORNDECARBOX-BIO-CPLX EG10961)
 (ENZYME ENTC-MONOMER EG10261) (ENZYME ENTB-CPLX EG10260)
 (ENZYME ENTA-CPLX EG10259)
 (ENZYME ENTMULTI-CPLX EG10263 EG10264 EG10262 EG10260)
 (ENZYME GLYCEROL-KIN-CPLX EG10398)
 (ENZYME GLYCPDIESTER-PERI-CPLX EG10399)
 (ENZYME GLYCPDIESTER-CYTO-MONOMER EG11050) (ENZYME GLYOXI-CPLX G6891)
 (ENZYME GLYOXII-MONOMER G6099) (ENZYME G7558-MONOMER G7558)
 (ENZYME MONOMER0-149 EG11648) (ENZYME MONOMER0-148 G7565)
 (ENZYME G6967-MONOMER G6967) (ENZYME GLYCDEH-CPLX EG11904)
 (ENZYME GLYOXIII-CPLX) (ENZYME LACTALDREDUCT-CPLX EG10351)
 (ENZYME PHENDEHYD-CPLX G7961)
 (ENZYME GLUCOSAMINE-6-P-DEAMIN-CPLX EG10633)
 (ENZYME NAG6PDEACET-CPLX EG10632) (ENZYME GABATRANSAM-CPLX EG10361)
 (ENZYME G6646-MONOMER G6646) (ENZYME G6811-MONOMER G6811)
 (ENZYME SUCCSEMIALDDEHYDROG-MONOMER EG11329)
 (ENZYME SUCCSEMIALDDEHYDROG-NAD-CPLX G99) (ENZYME CPLX-64 G6281)
 (ENZYME CPLX-7524 G6285) (ENZYME CROBETREDUCT-MONOMER EG11560)
 (ENZYME CARNDEHYDRA-CPLX EG11559) (ENZYME CARNRACE-MONOMER EG11557)
 (ENZYME CPLX0-3641 G6755) (ENZYME G7596-MONOMER G7596)
 (ENZYME CPLX0-3943 G6645) (ENZYME ALDHDEHYDROG-MONOMER EG10036)
 (ENZYME EG11822-MONOMER EG11822) (ENZYME G6644-MONOMER G6644)
 (ENZYME |E1(O)| EG10979) (ENZYME |E2(O)| EG10980)
 (ENZYME ALARACEBIOSYN-MONOMER EG10001) (ENZYME CPLX0-7465 EG11408)
 (ENZYME DALADEHYDROG-CPLX EG11407) (ENZYME ARGSUCCTRAN-MONOMER G6943)
 (ENZYME SUCCARGDIHYDRO-MONOMER G6941)
 (ENZYME SUCCORNTRANSAM-CPLX G6944)
 (ENZYME SUCCGLUALDDEHYD-MONOMER G6942)
 (ENZYME SUCCGLUDESUCC-MONOMER G6940) (ENZYME CYSLYDE-MONOMER)
 (ENZYME CYSTATHIONINE-BETA-LYASE-CPLX EG10583) (ENZYME GLUTAMINA-CPLX)
 (ENZYME GLUTAMINB-CPLX) (ENZYME G6810-MONOMER G6810)
 (ENZYME G6261-MONOMER G6261) (ENZYME GCVP-CPLX EG11810)
 (ENZYME GCVT-MONOMER EG11442) (ENZYME LYSDECARBOX-CPLX EG10131)
 (ENZYME LDC2-CPLX G6094) (ENZYME CPLX0-227 EG12423)
 (ENZYME PUTA-CPLX EG10801) (ENZYME LSERINEDEAM1-MONOMER EG10930)
 (ENZYME LSERINEDEAM2-MONOMER EG11623) (ENZYME CPLX0-7622 G7624)
 (ENZYME LTAA-CPLX G6455) (ENZYME THREDEHYDCAT-CPLX EG10990)
 (ENZYME PROPKIN-MONOMER EG11172) (ENZYME AMINEOXID-CPLX EG13139)
 (ENZYME THREODEHYD-CPLX EG10993) (ENZYME AKBLIG-CPLX EG10512)
 (ENZYME TRYPTOPHAN-CPLX EG11005) (ENZYME MHPCHYDROL-MONOMER M012)
 (ENZYME MHPHYDROXY-MONOMER M010)
 (ENZYME PHENPRODIOLDEHYDROG-MONOMER G7335)
 (ENZYME HCAMULTI-CPLX G7336 G7334 M015 M009)
 (ENZYME DHPDIOXYGEN-CPLX M011) (ENZYME G6719-MONOMER G6719)
 (ENZYME G6714-MONOMER G6714) (ENZYME G6716-MONOMER G6716)
 (ENZYME G6715-MONOMER G6715) (ENZYME G6718-MONOMER G6718)
 (ENZYME CPLX0-1762 G6713 G6712 G6711 G6710 G6709)
 (ENZYME G6208-MONOMER G6208) (ENZYME CPLX0-3954 EG12026)
 (ENZYME ADHC-CPLX EG50010) (ENZYME MHPDHYDROL-MONOMER M013)
 (ENZYME MHPELY-MONOMER G6205) (ENZYME EG10144-MONOMER EG10144)
 (ENZYME G6576-MONOMER G6576) (ENZYME GLUCDEHYDROG-MONOMER EG10369)
 (ENZYME G6437-MONOMER G6437) (ENZYME EG11470-MONOMER EG11470)
 (ENZYME EG11195-MONOMER EG11195) (ENZYME G6425-MONOMER G6425)
 (ENZYME GLUCOSE-1-PHOSPHAT-CPLX EG10033)
 (ENZYME EG11850-MONOMER EG11850)
 (ENZYME PHOSPHOGLUCMUT-MONOMER EG12144) (ENZYME LYXK-CPLX EG12284)
 (ENZYME EG12287-MONOMER EG12287) (ENZYME MANNPISOM-MONOMER EG10566)
 (ENZYME MANNKIN-MONOMER) (ENZYME EG13236-MONOMER EG13236)
 (ENZYME ALPHAGALACTOSID-CPLX EG10577) (ENZYME 1-PFK EG10337)
 (ENZYME EG11957-MONOMER EG11957) (ENZYME EG11956-MONOMER EG11956)
 (ENZYME RHAMNULPALDOL-CPLX EG11866)
 (ENZYME RHAMNULOKIN-MONOMER EG11868) (ENZYME CPLX0-7652 EG11867)
 (ENZYME CPLX0-7647 EG10818) (ENZYME CPLX0-7646 EG10817)
 (ENZYME CPLX0-7631 EG10349) (ENZYME FUCULOKIN-MONOMER EG10350)
 (ENZYME CPLX0-7633 EG10348) (ENZYME ALD-CPLX EG10035)
 (ENZYME ARABISOM-CPLX EG10052) (ENZYME RIBULPEPIM-CPLX EG10055)
 (ENZYME RIBULOKIN-CPLX EG10053) (ENZYME BETAGALACTOSID-CPLX EG10527)
 (ENZYME TREHALAPERI-MONOMER EG11017)
 (ENZYME TREHALACYTO-MONOMER EG12245)
 (ENZYME TRE6PHYDRO-MONOMER EG11402) (ENZYME GLUCOKIN-MONOMER EG12957)
 (ENZYME CPLX0-7466 EG11075) (ENZYME XYLISOM-CPLX EG11074)
 (ENZYME GLY3KIN-MONOMER G6283) (ENZYME GLYOCARBOLIG-CPLX EG11583)
 (ENZYME CPLX0-7616 G6278) (ENZYME MALSYNG-MONOMER EG20080)
 (ENZYME CPLX0-7458 G0-8601 G7544 G7545) (ENZYME G7859-MONOMER G7859)
 (ENZYME EG12286-MONOMER EG12286) (ENZYME G7858-MONOMER G7858)
 (ENZYME G7860-MONOMER G7860) (ENZYME G7855-MONOMER G7855)
 (ENZYME E1P-CPLX EG10024) (ENZYME E2P-MONOMER EG10025)
 (ENZYME E3-CPLX EG10543) (ENZYME METHYLMALONYL-COA-EPIM-MONOMER)
 (ENZYME PROPIONYL-COA-CARBOXY-MONOMER) (ENZYME ACS-MONOMER EG11448)
 (ENZYME CPLX0-251 G6198) (ENZYME G6199-MONOMER G6199)
 (ENZYME CPLX0-1021 G6196)
 (ENZYME METHYLMALONYL-COA-MUT-MONOMER EG11444)
 (ENZYME CPLX0-254 G7516) (ENZYME G7517-MONOMER G7517)
 (ENZYME ACETYL-COA-ACETYLTRANSFER-CPLX EG11672)
 (ENZYME ACETOACETYL-COA-TRANSFER-CPLX EG11669 EG11670)
 (ENZYME FAO-CPLX EG10278 EG10279) (ENZYME CPLX0-1668 G7213 G7212)
 (ENZYME ACYLCOASYN-CPLX EG11530) (ENZYME CPLX0-1669 EG12357)
 (ENZYME ACYLCOADEHYDROG-MONOMER G6105) (ENZYME G6918-MONOMER G6918)
 (ENZYME EG11811-MONOMER EG11811) (ENZYME FADB-CPLX EG10279)
 (ENZYME G6708-MONOMER G6708) (ENZYME CPLX0-1666 G7212)
 (ENZYME CARBODEHYDRAT-CPLX EG10176) (ENZYME CPLX0-7520 EG10175)
 (ENZYME CPLX0-224 G6479) (ENZYME CPLX0-225 G6477)
 (ENZYME PAPSSULFOTRANS-CPLX EG10189)
 (ENZYME SULFITE-REDUCT-CPLX EG10190 EG10191)
 (ENZYME ADENYLYLSULFKIN-CPLX EG10185)
 (ENZYME CPLX0-7428 EG10186 EG10194) (ENZYME URPHOS-CPLX EG11045)
 (ENZYME XANTHOSINEPHOSPHORY-CPLX G85) (ENZYME DEOD-CPLX EG10222)
 (ENZYME ADENODEAMIN-MONOMER EG10030) (ENZYME CYTIDEAM-CPLX EG10137)
 (ENZYME DEOA-CPLX EG10219) (ENZYME PPENTOMUT-MONOMER EG10220)
 (ENZYME DEOXYRIBOSE-P-ALD-MONOMER EG10221) (ENZYME MHPF-MONOMER M014)
 (ENZYME SUPEROX-DISMUTMN-CPLX EG10953)
 (ENZYME SUPEROX-DISMUTFE-CPLX EG10954) (ENZYME G6886-MONOMER G6886)
 (ENZYME HYDROPEROXIDII-CPLX EG10509)
 (ENZYME HYDROPEROXIDI-CPLX EG10511) (ENZYME G7263-MONOMER G7263)
 (ENZYME G6880-MONOMER G6880) (ENZYME CPLX0-821 G7723)
 (ENZYME G7726-MONOMER G7726) (ENZYME CPLX0-3861 G7724)
 (ENZYME GALACTARDEHYDRA-MONOMER EG12522)
 (ENZYME DEHYDDEOXGALACTKIN-MONOMER EG20051)
 (ENZYME DEHYDDEOXPHOSGALACT-ALDOL-MONOMER EG20049)
 (ENZYME GALACTONATE-DEHYDRATASE-MONOMER GB4478)
 (ENZYME CPLX0-7615 EG10016) (ENZYME TSA-REDUCT-MONOMER EG11176)
 (ENZYME G6278-MONOMER G6278) (ENZYME GLUCARDEHYDRA-MONOMER G7445)
 (ENZYME GKI-MONOMER EG11175) (ENZYME MANNONDEHYDRAT-MONOMER EG11066)
 (ENZYME MANNONOXIDOREDUCT-MONOMER EG20248) (ENZYME UXAC-MONOMER G81)
 (ENZYME BETA-GLUCURONID-MONOMER EG11055)
 (ENZYME GLUCONREDUCT-MONOMER G7892)
 (ENZYME GLUCONOKINI-MONOMER EG12152) (ENZYME IDONDEHYD-MONOMER G7893)
 (ENZYME G7945-MONOMER G7945)
 (ENZYME ALTRO-OXIDOREDUCT-MONOMER EG11065)
 (ENZYME ALTRODEHYDRAT-MONOMER EG12734)
 (ENZYME DEOXYGLUCONOKIN-MONOMER EG12253)
 (ENZYME CPLX0-240 G7631 EG12768) (ENZYME CPLX0-241 G7128 EG12419)
 (ENZYME GALACTITOLPDEHYD-MONOMER EG12417)
 (ENZYME MANNPDEHYDROG-MONOMER EG10616)
 (ENZYME SORB6PDEHYDROG-CPLX EG10971)
 (ENZYME ARGDECARBOXDEG-CPLX EG11501)
 (ENZYME GLUTDECARBOXA-CPLX EG50009)
 (ENZYME GLUTDECARBOXB-CPLX EG11490)
 (ENZYME KDPGALDOL-4OH2OXOGLUTARALDOL-CPLX EG10256)
 (ENZYME PGLUCONDEHYDRAT-MONOMER EG10257)
 (ENZYME PHOSACETYLTRANS-CPLX EG20173) (ENZYME ACETATEKINB-MONOMER G14)
 (ENZYME ACETATEKINA-MONOMER EG10027) (ENZYME ADHE-CPLX EG10031)
 (ENZYME ADHP-MONOMER G6775) (ENZYME DLACTDEHYDROGNAD-MONOMER G592)
 (ENZYME PYRUVOXID-CPLX EG10754) (ENZYME PHOSGLYCMUTASE EG11699)
 (ENZYME PGAM2-MONOMER EG12164) (ENZYME PGMI-MONOMER EG12296)
 (ENZYME PGK EG10703) (ENZYME GAPDH-A-CPLX EG10367)
 (ENZYME TPI EG11015) (ENZYME FRUCBISALD-CLASSII EG10282)
 (ENZYME FRUCBISALD-CLASSI G7129) (ENZYME 6PFK-2-CPX EG10700)
 (ENZYME 6PFK-1-CPX EG10699) (ENZYME PGLUCISOM EG10702)
 (ENZYME PEPSYNTH-CPLX EG10759) (ENZYME F16B-CPLX EG10283)
 (ENZYME CPLX0-303 EG11517) (ENZYME EG11239-MONOMER EG11239)
 (ENZYME TRANSALDOLB-CPLX EG11556) (ENZYME TRANSALDOLA-MONOMER EG11797)
 (ENZYME TRANSKETOI-CPLX EG11427) (ENZYME CPLX0-1261 EG12100)
 (ENZYME RIBULP3EPIM-MONOMER M004) (ENZYME RIB5PISOMB-CPLX EG11827)
 (ENZYME RIB5PISOMA-CPLX EG11443) (ENZYME 6PGLUCONOLACT-MONOMER G6397)
 (ENZYME 6PGLUCONDEHYDROG-CPLX EG10411)
 (ENZYME GLU6PDEHYDROG-MONOMER EG11221)
 (ENZYME AERGLYC3PDEHYDROG-CPLX EG10394)
 (ENZYME DLACTDEHYDROGFAD-MONOMER EG10231)
 (ENZYME NADH-DHII-MONOMER EG10649) (ENZYME PKII-CPLX EG10803)
 (ENZYME PKI-COMPLEX EG10804)
 (ENZYME PYRUVATEDEH-CPLX EG10543 EG10025 EG10024)
 (ENZYME PEPCARBOX-CPLX EG10756) (ENZYME KETOBUTFORMLY-MONOMER G7627)
 (ENZYME PYRUVFORMLY-CPLX EG10701) (ENZYME ENOLASE-CPLX EG10258)
 (ENZYME FHLMULTI-CPLX EG10477 EG10476 EG10479 EG10480 EG10475 EG10478
  EG10285)
 (ENZYME DIMESULFREDUCT-CPLX EG10234 EG10233 EG10232)
 (ENZYME CPLX0-1601 G6848 G6847 G6846 G6845)
 (ENZYME TMAOREDUCTII-MONOMER) (ENZYME THTOREDUCT-MONOMER)
 (ENZYME NAP-CPLX EG12064 EG12062 EG12060 EG12067 EG12061)
 (ENZYME CPLX-63 G7023 G7022) (ENZYME TMAOREDUCTI-CPLX EG11814 EG11815)
 (ENZYME FUMARATE-REDUCTASE EG10333 EG10332 EG10331 EG10330)
 (ENZYME NRFMULTI-CPLX EG11781 EG11945 EG11946 EG11947)
 (ENZYME CYTOCHROMEC552-MONOMER EG11781)
 (ENZYME ANGLYC3PDEHYDROG-CPLX EG10393 EG10392 EG10391)
 (ENZYME L-LACTDEHYDROGFMN-MONOMER EG11963)
 (ENZYME FORMATEDEHYDROGO-CPLX EG11856 EG11857 EG11858)
 (ENZYME FORMATEDEHYDROGN-CPLX EG11229 EG11228 EG11227)
 (ENZYME NADH-DHI-CPLX EG12083 EG12084 EG12089 EG12086 EG11774 EG12087
  EG12093 EG11773 EG12092 EG12091 EG12090 EG12088 EG12082)
 (ENZYME FORMHYDROGI-CPLX EG10470 EG10469 EG10468)
 (ENZYME FORMHYDROG2-CPLX EG11801 G7554 EG11800 EG11799)
 (ENZYME MALATE-SYNTHASE EG10023) (ENZYME ISOCIT-LYASE EG10022)
 (ENZYME MALATE-DEHASE EG10576) (ENZYME FUMARASE-C EG10358)
 (ENZYME FUMARASE-B EG10357) (ENZYME FUMARASE-A EG10356)
 (ENZYME SUCCCOASYN EG10981 EG10982)
 (ENZYME 2OXOGLUTARATEDEH-CPLX EG10543 EG10980 EG10979)
 (ENZYME ISOCITHASE-CPLX EG10489)
 (ENZYME |CITRATE-(SI)-SYNTHASE| EG10402)
 (ENZYME ACONITASE-MONOMER EG11325)
 (ENZYME ACONITATEDEHYDRB-MONOMER EG12316)
 (ENZYME SUCC-DEHASE EG10931 EG10932 EG10933 EG10934)
 (ENZYME EG12069-MONOMER EG12069))