(setq absent-essential-compounds '(ALA ASP DTTP))
(setq unproduceable-essential-compounds '(DATPDGTP))
(setq minimal-nutrient-set '(GLN ASN THR LEU VAL ILE TRP PHE TYR CYS MET LYS GLY ARG HIS PRO UDP-GALACTOSE UDP-GLUCOSE RIBULOSE-5P ADP-L-GLYCERO-D-MANNO-HEPTOSE GLC-1-P TTP FRUCTOSE-6P 3-OHMYRISTOYL-ACP GLT NADPH PHOSPHO-ENOL-PYRUVATE MESO-DIAMINOPIMELATE L-ALPHA-ALANINE D-ALANINE UDP-N-ACETYL-D-GLUCOSAMINE UNDECAPRENYL-P GTP GLYCEROL-3P SER CDPDIACYLGLYCEROL METHYLENE-THF UTP CTP UDP |Red-Glutaredoxins| |Red-Thioredoxin| |Reduced-flavodoxins| CDP ATP WATER DIACETYLCHITOBIOSE-6-PHOSPHATE))

(pathway-tools-file "minimal-nutrients.txt" minimal-nutrient-set)
