;; biohacker/trunk/network-debugger/tests/unknown.lisp
(network-debugger unknown :debugging t :rules :extended-reactions)

;; Network
(reaction 
 r1 
 :reactants (a b) 
 :products (c g)
 :enzymes (e1)
 :reversible? nil)

(reaction 
 r2
 :reactants (b c)
 :products (d)
 :enzymes (e2)
 :reversible? t)

(reaction 
 r3
 :reactants (d g)
 :products (e)
 :enzymes (e3))

(reaction 
 r4
 :reactants (b f)
 :products (e)
 :enzymes (e4))

(enzyme e1 g1)
(enzyme e2 g2)
(enzyme e3 g3 :unknown)
(enzyme e4 :unknown)

;; Experiments
(experiment
 growth-due-to-unknown
 (a b f)
 :growth? t
 :essential-compounds (a e)
 :knock-outs (g1))

(experiment
 no-growth-due-to-unknown
 (a b)
 :growth? nil
 :essential-compounds (a e))

(experiment
 no-growth-independent-of-unknowns
 (a)
 :growth? nil
 :essential-compounds (a e))

(summarize-findings)

#|
Network Debugger UNKNOWN
Adding reaction R1.
Adding reaction R2.
Adding reaction R3.
Adding reaction R4.
Adding enzyme E1.
Adding enzyme E2.
Adding enzyme E3.
Adding enzyme E4.
Closing network for EXPERIMENT.
Adding experiment GROWTH-DUE-TO-UNKNOWN
Assuming simplify-investigations.
Assuming unknown genes and reaction reversibilities as convenient.
Focusing on experiment GROWTH-DUE-TO-UNKNOWN.
Experiment GROWTH-DUE-TO-UNKNOWN is consistent with model.
Adding experiment NO-GROWTH-DUE-TO-UNKNOWN
Retracting focus on experiment GROWTH-DUE-TO-UNKNOWN.
Focusing on experiment NO-GROWTH-DUE-TO-UNKNOWN.
Experiment NO-GROWTH-DUE-TO-UNKNOWN is consistent with model.
Adding experiment NO-GROWTH-INDEPENDENT-OF-UNKNOWNS
Retracting focus on experiment NO-GROWTH-DUE-TO-UNKNOWN.
Focusing on experiment NO-GROWTH-INDEPENDENT-OF-UNKNOWNS.
Experiment NO-GROWTH-INDEPENDENT-OF-UNKNOWNS is consistent with model.
1 positive findings: (GROWTH-DUE-TO-UNKNOWN)
2 negative findings: (NO-GROWTH-INDEPENDENT-OF-UNKNOWNS NO-GROWTH-DUE-TO-UNKNOWN)
0 false-negative findings: NIL
0 false-positive findings: NIL
|#

#|
(explain 'growth)

  1 (FOCUS-EXPERIMENT GROWTH-DUE-TO-UNKNOWN) ()   Assumption
  2    (NUTRIENT A)             (1)  (:OR (NUTRIENT A) (:NOT (FOCUS-EXPERIMENT GROWTH-DUE-TO-UNKNOWN)))
  3 (COMPOUND-PRESENT A)        (2)  (:OR (COMPOUND-PRESENT A) (:NOT (NUTRIENT A)))
  4    (NUTRIENT F)             (1)  (:OR (NUTRIENT F) (:NOT (FOCUS-EXPERIMENT GROWTH-DUE-TO-UNKNOWN)))
  5 (COMPOUND-PRESENT F)        (4)  (:OR (COMPOUND-PRESENT F) (:NOT (NUTRIENT F)))
  6    (NUTRIENT B)             (1)  (:OR (NUTRIENT B) (:NOT (FOCUS-EXPERIMENT GROWTH-DUE-TO-UNKNOWN)))
  7 (COMPOUND-PRESENT B)        (6)  (:OR (COMPOUND-PRESENT B) (:NOT (NUTRIENT B)))
  8 EXPERIMENT-GROWTH           (1)  (:OR EXPERIMENT-GROWTH (:NOT (FOCUS-EXPERIMENT GROWTH-DUE-TO-UNKNOWN)))
  9 ASSUME-UNKNOWNS-AS-CONVENIENT ()   Assumption
 10 (UNKNOWN-GENE-ON-FOR E4)  (8 9)  (:OR (:NOT ASSUME-UNKNOWNS-AS-CONVENIENT) (:NOT EXPERIMENT-GROWTH) (UNKNOWN-GENE-ON-FOR E4))
 11 (ENZYME-PRESENT E4)        (10)  (:OR (:NOT (UNKNOWN-GENE-ON-FOR E4)) (ENZYME-PRESENT E4))
 12 (REACTION-ENABLED R4)      (11)  (:OR (:NOT (ENZYME-PRESENT E4)) (REACTION-ENABLED R4))
 13 (COMPOUND-PRESENT E)   (5 7 12)  (:OR (:NOT (REACTION-ENABLED R4)) (:NOT (COMPOUND-PRESENT B)) (:NOT (COMPOUND-PRESENT F)) (COMPOUND-PRESENT E))
 14          GROWTH        (1 3 13)  (:OR (:NOT (COMPOUND-PRESENT E)) (:NOT (COMPOUND-PRESENT A)) (:NOT (FOCUS-EXPERIMENT GROWTH-DUE-TO-UNKNOWN)) GROWTH)
14

  1 (FOCUS-EXPERIMENT NO-GROWTH-DUE-TO-UNKNOWN) ()   Assumption
  2 SIMPLIFY-INVESTIGATIONS           ()   Assumption
  3 (:NOT (NUTRIENT E))            (1 2)  (:OR (:NOT (NUTRIENT E)) (:NOT SIMPLIFY-INVESTIGATIONS) (:NOT (FOCUS-EXPERIMENT NO-GROWTH-DUE-TO-UNKNOWN)))
  4 (:NOT EXPERIMENT-GROWTH)         (1)  (:OR (:NOT EXPERIMENT-GROWTH) (:NOT (FOCUS-EXPERIMENT NO-GROWTH-DUE-TO-UNKNOWN)))
  5 ASSUME-UNKNOWNS-AS-CONVENIENT     ()   Assumption
  6 (:NOT (UNKNOWN-GENE-ON-FOR E3))(4 5)  (:OR (:NOT ASSUME-UNKNOWNS-AS-CONVENIENT) EXPERIMENT-GROWTH (:NOT (UNKNOWN-GENE-ON-FOR E3)))
  7 (UNKNOWN-GENE-FOR E3)            NIL  (:OR (UNKNOWN-GENE-FOR E3))
  8 (:NOT (ENZYME-PRESENT E3))     (6 7)  (:OR (:NOT (UNKNOWN-GENE-FOR E3)) (UNKNOWN-GENE-ON-FOR E3) (:NOT (ENZYME-PRESENT E3)))
  9 (:NOT (REACTION-ENABLED R3))   (8 4)  (:OR EXPERIMENT-GROWTH (ENZYME-PRESENT E3) (:NOT (REACTION-ENABLED R3)))
 10 (:NOT (REACTION-FIRED R3))       (9)  (:OR (REACTION-ENABLED R3) (:NOT (REACTION-FIRED R3)))
 11 (:NOT (UNKNOWN-GENE-ON-FOR E4))(4 5)  (:OR (:NOT ASSUME-UNKNOWNS-AS-CONVENIENT) EXPERIMENT-GROWTH (:NOT (UNKNOWN-GENE-ON-FOR E4)))
 12 (UNKNOWN-GENE-FOR E4)            NIL  (:OR (UNKNOWN-GENE-FOR E4))
 13 (:NOT (ENZYME-PRESENT E4))   (11 12)  (:OR (:NOT (UNKNOWN-GENE-FOR E4)) (UNKNOWN-GENE-ON-FOR E4) (:NOT (ENZYME-PRESENT E4)))
 14 (:NOT (REACTION-ENABLED R4))  (13 4)  (:OR EXPERIMENT-GROWTH (ENZYME-PRESENT E4) (:NOT (REACTION-ENABLED R4)))
 15 (:NOT (REACTION-FIRED R4))      (14)  (:OR (REACTION-ENABLED R4) (:NOT (REACTION-FIRED R4)))
 16 (:NOT (COMPOUND-PRESENT E))(3 10 15)  (:OR (REACTION-FIRED R4) (:NOT (COMPOUND-PRESENT E)) (REACTION-FIRED R3) (NUTRIENT E))
 17   (:NOT GROWTH)               (1 16)  (:OR (COMPOUND-PRESENT E) (:NOT GROWTH) (:NOT (FOCUS-EXPERIMENT NO-GROWTH-DUE-TO-UNKNOWN)))

  1 (FOCUS-EXPERIMENT NO-GROWTH-INDEPENDENT-OF-UNKNOWNS) ()   Assumption
  2 SIMPLIFY-INVESTIGATIONS            ()   Assumption
  3 (:NOT (NUTRIENT E))             (1 2)  (:OR (:NOT (NUTRIENT E)) (:NOT SIMPLIFY-INVESTIGATIONS) (:NOT (FOCUS-EXPERIMENT NO-GROWTH-INDEPENDENT-OF-UNKNOWNS)))
  4 (:NOT EXPERIMENT-GROWTH)          (1)  (:OR (:NOT EXPERIMENT-GROWTH) (:NOT (FOCUS-EXPERIMENT NO-GROWTH-INDEPENDENT-OF-UNKNOWNS)))
  5 ASSUME-UNKNOWNS-AS-CONVENIENT      ()   Assumption
  6 (:NOT (UNKNOWN-GENE-ON-FOR E3)) (4 5)  (:OR (:NOT ASSUME-UNKNOWNS-AS-CONVENIENT) EXPERIMENT-GROWTH (:NOT (UNKNOWN-GENE-ON-FOR E3)))
  7 (UNKNOWN-GENE-FOR E3)             NIL  (:OR (UNKNOWN-GENE-FOR E3))
  8 (:NOT (ENZYME-PRESENT E3))      (6 7)  (:OR (:NOT (UNKNOWN-GENE-FOR E3)) (UNKNOWN-GENE-ON-FOR E3) (:NOT (ENZYME-PRESENT E3)))
  9 (:NOT (REACTION-ENABLED R3))    (8 4)  (:OR EXPERIMENT-GROWTH (ENZYME-PRESENT E3) (:NOT (REACTION-ENABLED R3)))
 10 (:NOT (REACTION-FIRED R3))        (9)  (:OR (REACTION-ENABLED R3) (:NOT (REACTION-FIRED R3)))
 11 (:NOT (UNKNOWN-GENE-ON-FOR E4)) (4 5)  (:OR (:NOT ASSUME-UNKNOWNS-AS-CONVENIENT) EXPERIMENT-GROWTH (:NOT (UNKNOWN-GENE-ON-FOR E4)))
 12 (UNKNOWN-GENE-FOR E4)             NIL  (:OR (UNKNOWN-GENE-FOR E4))
 13 (:NOT (ENZYME-PRESENT E4))    (11 12)  (:OR (:NOT (UNKNOWN-GENE-FOR E4)) (UNKNOWN-GENE-ON-FOR E4) (:NOT (ENZYME-PRESENT E4)))
 14 (:NOT (REACTION-ENABLED R4))   (13 4)  (:OR EXPERIMENT-GROWTH (ENZYME-PRESENT E4) (:NOT (REACTION-ENABLED R4)))
 15 (:NOT (REACTION-FIRED R4))       (14)  (:OR (REACTION-ENABLED R4) (:NOT (REACTION-FIRED R4)))
 16 (:NOT (COMPOUND-PRESENT E)) (3 10 15)  (:OR (REACTION-FIRED R4) (:NOT (COMPOUND-PRESENT E)) (REACTION-FIRED R3) (NUTRIENT E))
 17   (:NOT GROWTH)                (1 16)  (:OR (COMPOUND-PRESENT E) (:NOT GROWTH) (:NOT (FOCUS-EXPERIMENT NO-GROWTH-INDEPENDENT-OF-UNKNOWNS)))

|#